let me=null,data={},editing={product:null,category:null,payment:null,banner:null};let lastNotificationSignature="";
const api=async(u,o={})=>{
  let r;
  try{r=await fetch(u,o)}catch(e){throw Error('تعذر الاتصال بالخادم. تأكد أن الموقع منشور بشكل صحيح ثم حاول مرة أخرى.')}
  const d=await r.json().catch(()=>({}));
  if(!r.ok){
    const raw=String(d.error||'');
    if(/fetch failed|failed to fetch|network/i.test(raw)) throw Error('تعذر الاتصال بقاعدة البيانات. راجع إعدادات Supabase في Vercel.');
    throw Error(raw||'حدثت مشكلة أثناء تنفيذ العملية. حاول مرة أخرى.');
  }
  return d;
};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const post=b=>api('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});
const patch=b=>api('/api/admin',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(b)});
const del=(table,id)=>api('/api/admin',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({table,id})});
const val=id=>document.getElementById(id).value;
const set=(id,v)=>{document.getElementById(id).value=v??''};
function setMsg(id,msg,ok=true){const x=document.getElementById(id);if(x){x.textContent=msg;x.className='admin-muted '+(ok?'success':'')}}
function notice(title,text){const box=document.getElementById('adminNotice'),t=document.getElementById('adminNoticeTitle'),p=document.getElementById('adminNoticeText');if(!box)return alert(text);t.textContent=title||'Complete the required fields';p.textContent=text||'Please fill in the required information before continuing.';box.classList.remove('hidden');box.classList.remove('shake');void box.offsetWidth;box.classList.add('shake');document.getElementById('adminNoticeOk')?.focus()}
function closeNotice(){document.getElementById('adminNotice')?.classList.add('hidden')}
document.getElementById('adminNoticeOk')?.addEventListener('click',closeNotice);
document.getElementById('adminNotice')?.addEventListener('click',e=>{if(e.target.id==='adminNotice')closeNotice()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeNotice()});
function requireFields(fields){for(const f of fields){const el=document.getElementById(f.id);if(!el)continue;const value=String(el.value||'').trim();if(!value){notice('Missing information',`Please enter ${f.name}.`);el.focus();return false}}return true}
async function uploadImage(file){
  if(!file) return '';
  const fd=new FormData(); fd.append('file',file);
  const r=await fetch('/api/upload-image',{method:'POST',body:fd,credentials:'same-origin'});
  const d=await r.json().catch(()=>({}));
  if(!r.ok) throw Error(d.error||'Image upload failed');
  return d.url||'';
}
async function fileOrExisting(fileId,urlId){const f=document.getElementById(fileId)?.files?.[0];return f?await uploadImage(f):(document.getElementById(urlId)?.value||'')}
async function uploadMany(fileId){const fs=[...(document.getElementById(fileId)?.files||[])];const out=[];for(const f of fs)out.push(await uploadImage(f));return out}
function optionRows(){return [...document.querySelectorAll('.option-row')].map((r,i)=>({name:r.querySelector('.opt-name').value.trim(),price:Number(r.querySelector('.opt-price').value||0),old_price:Number(r.querySelector('.opt-old').value||0),image_url:r.querySelector('.opt-image').value.trim(),sort_order:i})).filter(x=>x.name)}
function renderOptionRows(opts=[]){const box=document.getElementById('productOptionsEditor');if(!box)return;box.innerHTML=(opts.length?opts:[{name:'',price:'',old_price:'',image_url:''}]).map((o,i)=>`<div class="option-row"><input class="opt-name" placeholder="Type name e.g. Home" value="${esc(o.name||'')}"><input class="opt-price" type="number" placeholder="Price" value="${o.price??''}"><input class="opt-old" type="number" placeholder="Old price" value="${o.old_price??''}"><input class="opt-image" placeholder="Option image URL (optional)" value="${esc(o.image_url||'')}"><button type="button" class="small-btn danger remove-option">×</button></div>`).join('');box.querySelectorAll('.remove-option').forEach(b=>b.onclick=()=>{b.parentElement.remove()})}
function addOptionRow(){const box=document.getElementById('productOptionsEditor');if(!box)return;const d=document.createElement('div');d.className='option-row';d.innerHTML='<input class="opt-name" placeholder="Type name e.g. Home"><input class="opt-price" type="number" placeholder="Price"><input class="opt-old" type="number" placeholder="Old price"><input class="opt-image" placeholder="Option image URL (optional)"><button type="button" class="small-btn danger remove-option">×</button>';d.querySelector('.remove-option').onclick=()=>d.remove();box.appendChild(d)}


async function init(){
  try{
    const r=await fetch('/api/admin',{credentials:'same-origin'});
    if(!r.ok)throw Error('Admin login required');
    document.querySelector('#gate').classList.add('hidden');
    document.querySelector('#panel').classList.remove('hidden');
    await refresh();
  }catch(e){
    document.querySelector('#gate').classList.remove('hidden');
  }
}
function setupLogin(){
  const form=document.querySelector('#adminLoginForm'); if(!form)return;
  form.addEventListener('submit',async e=>{
    e.preventDefault();
    setMsg('loginMsg','Logging in...',true);
    try{
      await api('/api/admin-login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:val('adminPassword')})});
      form.reset(); document.querySelector('#gate').classList.add('hidden');document.querySelector('#panel').classList.remove('hidden');await refresh();
    }catch(err){setMsg('loginMsg',err.message,false)}
  });
}
async function refresh(){data=await api('/api/admin');render();populateSelects();renderAdmins();lastNotificationSignature=(data.notifications||[]).filter(n=>!n.read).map(n=>n.id).join(',');startNotificationPolling()}
function render(){
 document.querySelector('#statProducts').textContent=(data.products||[]).length;document.querySelector('#statCategories').textContent=(data.categories||[]).length;document.querySelector('#statOrders').textContent=(data.orders||[]).length;document.querySelector('#statBanners').textContent=(data.banners||[]).length;const unread=(data.notifications||[]).filter(n=>!n.read);const nb=document.querySelector('#notificationBadge');if(nb){nb.textContent=unread.length;nb.classList.toggle('hidden',unread.length===0)}
 document.querySelector('#catList').innerHTML=(data.categories||[]).map(c=>`<div class="admin-item"><div class="admin-main"><b>${esc(c.name)}</b><div class="admin-muted">${esc(c.description||'')}</div></div><div class="admin-actions"><button class="small-btn" onclick="editCategory('${c.id}')">Edit</button><button class="small-btn danger" onclick="removeItem('categories','${c.id}')">Delete</button></div></div>`).join('')||'<p class="admin-muted">No categories.</p>';
 document.querySelector('#prodList').innerHTML=(data.products||[]).map(p=>{const opts=(data.options||[]).filter(o=>o.product_id===p.id);return `<div class="admin-item"><div class="admin-main"><b>${esc(p.name)}</b><div class="admin-muted">${esc(p.platform)} · ${p.price} EGP${p.old_price?` · Old ${p.old_price} EGP`:''} · ${opts.length} options</div></div><div class="admin-actions"><button class="small-btn" onclick="editProduct('${p.id}')">Edit</button><button class="small-btn danger" onclick="removeItem('products','${p.id}')">Delete</button></div></div>`}).join('')||'<p class="admin-muted">No products.</p>';
 document.querySelector('#payList').innerHTML=(data.payments||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(p=>`<div class="admin-item"><div class="admin-main"><b>${esc(p.name)}</b><div class="admin-muted">${esc(p.details)} · ${p.active?'Active':'Hidden'}</div></div><div class="admin-actions"><button class="small-btn" onclick="editPayment('${p.id}')">Edit</button><button class="small-btn" onclick="togglePayment('${p.id}')">${p.active?'Hide':'Activate'}</button><button class="small-btn danger" onclick="removeItem('payment_methods','${p.id}')">Delete</button></div></div>`).join('')||'<p class="admin-muted">No payment methods.</p>';
 document.querySelector('#bannerList').innerHTML=(data.banners||[]).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)).map(b=>`<div class="admin-item"><div class="admin-main"><b>${esc(b.title)}</b><div class="admin-muted">${esc(b.text)} · ${b.active?'Active':'Hidden'}</div>${b.image_url?`<img class="admin-preview" src="${esc(b.image_url)}" alt="">`:''}</div><div class="admin-actions"><button class="small-btn" onclick="editBanner('${b.id}')">Edit</button><button class="small-btn" onclick="toggleBanner('${b.id}')">${b.active?'Hide':'Activate'}</button><button class="small-btn danger" onclick="removeItem('hero_banners','${b.id}')">Delete</button></div></div>`).join('')||'<p class="admin-muted">No banners.</p>';
 document.querySelector('#discountList').innerHTML=(data.discounts||[]).map(d=>`<div class="admin-item"><div class="admin-main"><b>${esc(d.code)}</b><div class="admin-muted">${d.value}${d.kind==='percent'?'%':' EGP'} · ${esc(d.scope)} · ${d.active?'Active':'Hidden'}</div></div><div class="admin-actions"><button class="small-btn" onclick="toggleDiscount('${d.id}')">${d.active?'Disable':'Enable'}</button><button class="small-btn danger" onclick="removeItem('discounts','${d.id}')">Delete</button></div></div>`).join('')||'<p class="admin-muted">No discounts.</p>';
 const s=(data.settings||[])[0]||{};set('setName',s.store_name||'FLASH STORE');set('setLogo',s.logo_url||'');set('setAboutTitle',s.about_title||'About FLASH STORE');set('setAbout',s.about_text||'');set('setWa',s.whatsapp||'');set('setSupportTitle',s.support_title||'Support');set('setSupportText',s.support_text||'Need help? Contact us on WhatsApp.');
 document.querySelector('#orderList').innerHTML=(data.orders||[]).map(o=>`<div class="admin-item order-admin-card"><div class="admin-main"><b>#${esc(o.order_number)} — ${esc(o.full_name)}</b><div class="admin-muted"><b>Email:</b> ${esc(o.email)} · <b>Phone:</b> ${esc(o.phone)}</div><div class="admin-muted"><b>Payment:</b> ${esc(o.payment_method)} · <b>Payment details:</b> ${esc(o.payment_details||'')} · <b>Total:</b> ${Number(o.total||0).toLocaleString()} EGP</div><div class="admin-muted"><b>Order date:</b> ${new Date(o.created_at).toLocaleString()}</div>${o.discount_code?`<div class="admin-muted"><b>Discount:</b> ${esc(o.discount_code)} · ${Number(o.discount_amount||0).toLocaleString()} EGP</div>`:''}${o.account_email?`<div class="admin-muted"><b>Product Email:</b> ${esc(o.account_email)} · <b>Password:</b> ${esc(o.account_password||'')}</div>`:''}${o.proof_url?`<div class="admin-actions-row"><a class="small-btn" href="${esc(o.proof_url)}" target="_blank" rel="noopener">Open Payment Proof</a></div>`:'<div class="admin-muted">Payment proof missing</div>'}${(o.items||[]).length?`<div class="order-items-admin"><b>Products:</b>${o.items.map(i=>`<div class="order-item-admin">${i.image_url?`<img src="${esc(i.image_url)}" alt="">`:''}<span><b>${esc(i.product_name||'Product')}</b>${i.option_name?` · ${esc(i.option_name)}`:''} · Qty ${Number(i.quantity||1)} · ${Number(i.unit_price||0).toLocaleString()} EGP</span></div>`).join('')}</div>`:''}</div><div class="admin-actions"><span class="badge">${esc(o.status)}</span><button class="small-btn" onclick="statusOrder('${o.id}','processing')">Processing</button><button class="small-btn" onclick="statusOrder('${o.id}','completed')">Completed</button><button class="small-btn danger" onclick="statusOrder('${o.id}','cancelled')">Cancel</button></div></div>`).join('')||'<p class="admin-muted">No orders.</p>';
 document.querySelector('#notificationList').innerHTML=(data.notifications||[]).map(n=>`<div class="admin-item ${n.read?'':'notification-unread'}"><div class="admin-main"><b>${esc(n.title)}</b><div class="admin-muted">${esc(n.message)}</div><small class="admin-muted">${new Date(n.created_at).toLocaleString()}</small></div><div class="admin-actions">${n.read?'':'<button class="small-btn" onclick="markNotification(\''+n.id+'\')">Mark read</button>'}</div></div>`).join('')||'<p class="admin-muted">No notifications.</p>';
}
function populateSelects(){document.querySelector('#pCategory').innerHTML='<option value="">No category</option>'+(data.categories||[]).map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');document.querySelector('#bProduct').innerHTML='<option value="">No product / Products page</option>'+(data.products||[]).map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}
function resetProduct(){editing.product=null;['pName','pPlatform','pPrice','pOldPrice','pImage','pDescription'].forEach(x=>set(x,''));if(document.getElementById('pImageFile'))document.getElementById('pImageFile').value='';document.getElementById('productImagePreview').innerHTML='';set('pCategory','');['pFeatured','pBest','pDiscount'].forEach(x=>document.getElementById(x).checked=false);document.getElementById('pActive').checked=true;document.getElementById('pRequiresAccount').checked=false;renderOptionRows([]);document.getElementById('saveProduct').textContent='Add Product';document.getElementById('cancelProduct').classList.add('hidden')}
function resetCategory(){editing.category=null;['cName','cDescription','cImage'].forEach(x=>set(x,''));if(document.getElementById('cImageFile'))document.getElementById('cImageFile').value='';set('cSort',0);set('cActive','true');document.getElementById('saveCategory').textContent='Add Category';document.getElementById('cancelCategory').classList.add('hidden')}
function resetPayment(){editing.payment=null;['payName','payDetails'].forEach(x=>set(x,''));set('paySort',0);set('payActive','true');document.getElementById('savePayment').textContent='Add Payment Method';document.getElementById('cancelPayment').classList.add('hidden')}
function resetBanner(){editing.banner=null;['bTitle','bText','bImage','bOverlayTitle','bOverlayText'].forEach(x=>set(x,''));if(document.getElementById('bImageFile'))document.getElementById('bImageFile').value='';set('bButton','BUY NOW');set('bProduct','');set('bOverlay','false');set('bOverlayPosition','bottom-left');set('bOverlayButton','BUY NOW');document.getElementById('bShowPrice').checked=true;document.getElementById('bShowCategory').checked=true;set('bSort',0);set('bActive','true');document.getElementById('saveBanner').textContent='Add Banner';document.getElementById('cancelBanner').classList.add('hidden')}
window.editProduct=id=>{const p=data.products.find(x=>x.id===id);if(!p)return;editing.product=id;set('pName',p.name);set('pPlatform',p.platform);set('pPrice',p.price);set('pOldPrice',p.old_price);set('pImage',p.image_url);set('pDescription',p.description);set('pCategory',p.category_id||'');document.getElementById('pRequiresAccount').checked=!!p.requires_account_details;document.getElementById('pFeatured').checked=!!p.featured;document.getElementById('pBest').checked=!!p.best_seller;document.getElementById('pDiscount').checked=!!p.discount_badge;document.getElementById('pActive').checked=!!p.active;renderOptionRows((data.options||[]).filter(o=>o.product_id===id));document.getElementById('productImagePreview').innerHTML=(p.images||[]).map(x=>`<img src="${esc(x)}" class="admin-thumb">`).join('');document.getElementById('saveProduct').textContent='Save Product';document.getElementById('cancelProduct').classList.remove('hidden')};
window.editCategory=id=>{const c=data.categories.find(x=>x.id===id);editing.category=id;set('cName',c.name);set('cDescription',c.description);set('cImage',c.image_url);set('cSort',c.sort_order);set('cActive',String(c.active));document.getElementById('saveCategory').textContent='Save Category';document.getElementById('cancelCategory').classList.remove('hidden')};
window.editPayment=id=>{const p=data.payments.find(x=>x.id===id);editing.payment=id;set('payName',p.name);set('payDetails',p.details);set('paySort',p.sort_order);set('payActive',String(p.active));document.getElementById('savePayment').textContent='Save Payment Method';document.getElementById('cancelPayment').classList.remove('hidden')};
window.editBanner=id=>{const b=data.banners.find(x=>x.id===id);editing.banner=id;set('bTitle',b.title);set('bText',b.text);set('bImage',b.image_url);set('bButton',b.button_text||'BUY NOW');set('bProduct',b.product_id||'');set('bOverlayTitle',b.overlay_title||'');set('bOverlayText',b.overlay_text||'');set('bOverlay',String(!!b.overlay_enabled));set('bOverlayPosition',b.overlay_position||'bottom-left');set('bOverlayButton',b.overlay_button_text||b.button_text||'BUY NOW');document.getElementById('bShowPrice').checked=b.overlay_show_price!==false;document.getElementById('bShowCategory').checked=b.overlay_show_category!==false;set('bSort',b.sort_order);set('bActive',String(b.active));document.getElementById('saveBanner').textContent='Save Banner';document.getElementById('cancelBanner').classList.remove('hidden')};
window.removeItem=async(t,id)=>{confirmAction('Delete this item?', 'This cannot be undone.', async()=>{await del(t,id);await refresh()})};
window.togglePayment=async id=>{const p=data.payments.find(x=>x.id===id);await post({type:'payment',id,name:p.name,details:p.details,sort_order:p.sort_order,active:!p.active});await refresh()};
window.toggleBanner=async id=>{const b=data.banners.find(x=>x.id===id);await post({type:'banner',id,title:b.title,text:b.text,image_url:b.image_url,button_text:b.button_text,product_id:b.product_id,overlay_enabled:b.overlay_enabled,overlay_title:b.overlay_title,overlay_text:b.overlay_text,overlay_show_price:b.overlay_show_price,overlay_show_category:b.overlay_show_category,overlay_button_text:b.overlay_button_text,overlay_position:b.overlay_position,sort_order:b.sort_order,active:!b.active});await refresh()};
window.toggleDiscount=async id=>{const d=data.discounts.find(x=>x.id===id);await post({type:'discount_update',id,active:!d.active});await refresh()};
window.statusOrder=async(id,status)=>{await patch({type:'order',id,status});await refresh()};
document.getElementById('addOptionRow')?.addEventListener('click',addOptionRow);document.getElementById('pImageFile')?.addEventListener('change',()=>{const box=document.getElementById('productImagePreview');box.innerHTML=[...(document.getElementById('pImageFile').files||[])].map(f=>`<span class="admin-file-name">${esc(f.name)}</span>`).join('')});renderOptionRows([]);document.getElementById('saveProduct').onclick=async()=>{
  if(!requireFields([{id:'pName',name:'the product name'},{id:'pPlatform',name:'the platform'},{id:'pPrice',name:'the price'}]))return;
  try{setMsg('productMsg','Saving...');const picked=await uploadMany('pImageFile');let existing=[];try{existing=JSON.parse(val('pImage')||'[]')}catch{existing=val('pImage')?[val('pImage')]:[]}const images=[...picked,...existing.filter(x=>!picked.includes(x))];const b={type:'product',id:editing.product||undefined,name:val('pName').trim(),platform:val('pPlatform').trim(),price:Number(val('pPrice')||0),old_price:Number(val('pOldPrice')||0),requires_account_details:document.getElementById('pRequiresAccount').checked,image_url:images[0]||'',images,description:val('pDescription').trim(),category_id:val('pCategory')||null,featured:document.getElementById('pFeatured').checked,best_seller:document.getElementById('pBest').checked,discount_badge:document.getElementById('pDiscount').checked,active:document.getElementById('pActive').checked,options:optionRows()};await post(b);setMsg('productMsg','Saved');resetProduct();await refresh()}catch(e){setMsg('productMsg',e.message,false);notice('Couldn’t save product',e.message)}};
document.getElementById('cancelProduct').onclick=resetProduct;
document.getElementById('saveCategory').onclick=async()=>{
  if(!requireFields([{id:'cName',name:'the category name'}]))return;
  try{const b={type:'category',id:editing.category||undefined,name:val('cName').trim(),description:val('cDescription'),image_url:await fileOrExisting('cImageFile','cImage'),sort_order:Number(val('cSort')||0),active:val('cActive')==='true'};await post(b);resetCategory();await refresh()}catch(e){notice('Couldn’t save category',e.message)}};document.getElementById('cancelCategory').onclick=resetCategory;
document.getElementById('savePayment').onclick=async()=>{
  if(!requireFields([{id:'payName',name:'the payment method name'},{id:'payDetails',name:'the payment number or account details'}]))return;
  try{const b={type:'payment',id:editing.payment||undefined,name:val('payName').trim(),details:val('payDetails'),sort_order:Number(val('paySort')||0),active:val('payActive')==='true'};await post(b);resetPayment();await refresh()}catch(e){notice('Couldn’t save payment method',e.message)}};document.getElementById('cancelPayment').onclick=resetPayment;
document.getElementById('saveBanner').onclick=async()=>{
  if(!requireFields([{id:'bTitle',name:'the banner title'},{id:'bText',name:'the banner text'}]))return;
  const file=document.getElementById('bImageFile')?.files?.[0];const existing=val('bImage');if(!file&&!existing){notice('Missing information','Please choose a hero banner image from your computer.');return}
  try{const b={type:'banner',id:editing.banner||undefined,title:val('bTitle').trim(),text:val('bText').trim(),image_url:await fileOrExisting('bImageFile','bImage'),button_text:val('bButton')||'BUY NOW',product_id:val('bProduct')||null,overlay_enabled:val('bOverlay')==='true',overlay_title:val('bOverlayTitle').trim(),overlay_text:val('bOverlayText').trim(),overlay_show_price:document.getElementById('bShowPrice').checked,overlay_show_category:document.getElementById('bShowCategory').checked,overlay_button_text:val('bOverlayButton')||'BUY NOW',overlay_position:val('bOverlayPosition'),sort_order:Number(val('bSort')||0),active:val('bActive')==='true'};await post(b);resetBanner();await refresh()}catch(e){notice('Couldn’t save banner',e.message)}};document.getElementById('cancelBanner').onclick=resetBanner;
document.getElementById('saveDiscount').onclick=async()=>{
  if(!requireFields([{id:'dCode',name:'the discount code'},{id:'dValue',name:'the discount value'}]))return;
  try{const b={type:'discount',code:val('dCode').trim(),value:Number(val('dValue')||0),kind:val('dKind'),scope:val('dScope'),first_order_only:document.getElementById('dFirst').checked,one_use_per_user:document.getElementById('dOne').checked,max_uses:val('dMax')?Number(val('dMax')):null};await post(b);['dCode','dValue','dMax'].forEach(x=>set(x,''));await refresh()}catch(e){notice('Couldn’t save discount',e.message)}};
document.getElementById('saveSettings').onclick=async()=>{try{await post({type:'settings',store_name:val('setName'),logo_url:val('setLogo'),about_title:val('setAboutTitle'),about_text:val('setAbout'),whatsapp:val('setWa'),support_title:val('setSupportTitle'),support_text:val('setSupportText')});setMsg('settingsMsg','Settings saved');await refresh()}catch(e){notice('Couldn’t save settings',e.message)}};
document.getElementById('saveAdminRole').onclick=async()=>{
  if(!requireFields([{id:'adminEmail',name:'the user email'}]))return;
  try{await post({type:'admin_role',email:val('adminEmail').trim(),role:val('adminRole')});set('adminEmail','');await refresh()}catch(e){notice('Couldn’t update admin role',e.message)}};
function renderAdmins(){document.querySelector('#adminList').innerHTML=(data.profiles||[]).filter(x=>x.role==='admin').map(x=>`<div class="admin-item"><div class="admin-main"><b>${esc(x.email)}</b><div class="admin-muted">${esc(x.full_name||'')}</div></div><button class="small-btn" onclick="demoteAdmin('${esc(x.email)}')">Make Client</button></div>`).join('')||'<p class="admin-muted">No admins found.</p>'}
window.demoteAdmin=async email=>{confirmAction('Change this role?', 'This user will become a normal client.', async()=>{await post({type:'admin_role',email,role:'client'});await refresh()})};
document.querySelectorAll('#tabs button').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.admin-section').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('tab-'+btn.dataset.tab).classList.add('active')});
window.markNotification=async id=>{await post({type:'notification_read',id});await refresh()};
document.getElementById('markAllNotifications')?.addEventListener('click',async()=>{await post({type:'notifications_read_all'});await refresh()});
let confirmPending=null;function confirmAction(title,text,action){const m=document.getElementById('confirmModal');if(!m)return Promise.resolve().then(action);document.getElementById('confirmTitle').textContent=title;document.getElementById('confirmText').textContent=text;confirmPending=action;m.classList.remove('hidden');document.getElementById('confirmOk').focus()}function closeConfirm(){document.getElementById('confirmModal')?.classList.add('hidden');confirmPending=null}document.getElementById('confirmCancel')?.addEventListener('click',closeConfirm);document.getElementById('confirmModal')?.addEventListener('click',e=>{if(e.target.id==='confirmModal')closeConfirm()});document.getElementById('confirmOk')?.addEventListener('click',async()=>{const fn=confirmPending;closeConfirm();if(fn)try{await fn()}catch(e){notice('Action failed',e.message)}});
let pollTimer;function startNotificationPolling(){clearInterval(pollTimer);pollTimer=setInterval(async()=>{try{const old=(data.notifications||[]).filter(n=>!n.read);const fresh=await api('/api/admin');data=fresh;const now=(data.notifications||[]).filter(n=>!n.read);const sig=now.map(n=>n.id).join(',');if(lastNotificationSignature&&sig!==lastNotificationSignature&&now.length>old.length){const n=now[0];notice(n.title,n.message)}lastNotificationSignature=sig;render();populateSelects();renderAdmins()}catch(_){ }},12000)}
document.getElementById('logout').onclick=async()=>{clearInterval(pollTimer);await api('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({type:'logout'})});location.reload()};
setupLogin();
init();
