const KEY='flash_store_v2';
const demo={settings:{whatsapp:'201000000000',storeName:'Flash Store',slogan:'MORE THAN A STORE ⚡'},categories:[['fortnite','Fortnite'],['fc27','EA FC 27'],['xbox','Xbox'],['gamepass','Xbox Game Pass'],['playstation','PlayStation'],['steam','Steam'],['giftcards','Gift Cards']].map(([id,name])=>({id,name,image:'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=900'})),products:[],orders:[],users:[]};
demo.products=[['fortnite','Fortnite Crew',250,'FULL'],['fortnite','800 V-Bucks',350,'FULL'],['fortnite','2400 V-Bucks',650,'FULL'],['gamepass','Game Pass Ultimate 4 Months',700,'HOME'],['fc27','EA FC 27 Standard',3400,'FULL'],['fc27','EA FC 27 Ultimate',4400,'FULL'],['xbox','ARC Raiders',700,'HOME'],['xbox','GTA V',500,'HOME']].map(x=>({id:crypto.randomUUID(),cat:x[0],name:x[1],desc:'Digital product — fast delivery.',image:'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=900',options:[{name:x[3],price:x[2]}],old:0}));
let data=JSON.parse(localStorage.getItem(KEY)||'null')||demo; let selectedUser=JSON.parse(localStorage.getItem('flash_user')||'null');
function save(){localStorage.setItem(KEY,JSON.stringify(data))} function $(s){return document.querySelector(s)} function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))} function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',1800)} function modal(id,on=true){$('#'+id).classList.toggle('show',on)}
document.addEventListener('click',e=>{if(e.target.dataset.close)modal(e.target.dataset.close,false)});
function render(){renderCats();renderOffers();renderOrders();$('#year').textContent=new Date().getFullYear();$('#wa').href='https://wa.me/'+data.settings.whatsapp;renderAccountButton()}
function renderCats(){$('#cats').innerHTML=data.categories.length?data.categories.map(c=>`<article class="category" data-cat="${esc(c.id)}"><img src="${esc(c.image)}"><div><b>${esc(c.name)}</b></div></article>`).join(''):'<div class="empty">No categories yet.</div>';document.querySelectorAll('.category').forEach(x=>x.onclick=()=>showCat(x.dataset.cat))}
function showCat(id){let c=data.categories.find(x=>x.id===id);if(!c)return;$('#products').classList.remove('hide');$('#offers').classList.add('hide');$('#catTitle').textContent=c.name;let ps=data.products.filter(p=>p.cat===id);$('#prods').innerHTML=ps.length?ps.map(productCard).join(''):'<div class="empty">No products yet.</div>';bindProducts('#prods');location.hash='products'}
function productCard(p){let o=p.options?.[0]||{price:0};return `<article class="product" data-id="${esc(p.id)}"><img src="${esc(p.image)}"><div><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p><span class="price">${o.price} EGP</span>${p.old?`<span class="old">${p.old} EGP</span>`:''}</div></article>`}
function bindProducts(sel){document.querySelectorAll(sel+' .product').forEach(x=>x.onclick=()=>showProduct(x.dataset.id))}
function renderOffers(){let ps=data.products.filter(p=>p.old&&p.old>p.options[0].price);$('#offersGrid').innerHTML=ps.length?ps.map(productCard).join(''):'<div class="empty">No offers right now.</div>';bindProducts('#offersGrid')}
function showProduct(id){let p=data.products.find(x=>x.id===id);if(!p)return;$('#pmImg').src=p.image;$('#pmName').textContent=p.name;$('#pmDesc').textContent=p.desc||'';$('#pmCat').textContent=data.categories.find(c=>c.id===p.cat)?.name||'';let idx=0;function update(){document.querySelectorAll('#opts .option').forEach((x,i)=>x.classList.toggle('selected',i===idx));$('#pmPrice').textContent=(p.options[idx]?.price||0)+' EGP'}$('#opts').innerHTML=(p.options||[]).map((o,i)=>`<div class="option" data-i="${i}"><b>${esc(o.name)}</b><strong>${o.price} EGP</strong></div>`).join('');document.querySelectorAll('#opts .option').forEach(x=>x.onclick=()=>{idx=+x.dataset.i;update()});update();$('#order').onclick=()=>placeOrder(p,p.options[idx]);modal('productModal')}
function placeOrder(p,o){if(!selectedUser){modal('productModal',false);openAuth('login');toast('Please login or sign up first');return}let order={id:data.orders.length+1,product:p.name,option:o.name,price:o.price,user:selectedUser.email,name:selectedUser.name,status:'New',date:new Date().toLocaleString()};data.orders.push(order);save();renderOrders();let msg=encodeURIComponent(`Hello Flash Store!\nOrder ${order.id}\nProduct: ${p.name}\nOption: ${o.name}\nPrice: ${o.price} EGP\nName: ${selectedUser.name}`);window.open('https://wa.me/'+data.settings.whatsapp+'?text='+msg,'_blank');modal('productModal',false);toast('Order created!')}
function renderOrders(){let my=selectedUser?data.orders.filter(o=>o.user===selectedUser.email):[];$('#orderBox').innerHTML=my.length?my.map(o=>`<div class="orderrow"><div><b>Order ${o.id}</b><br>${esc(o.product)} — ${esc(o.option)}<br><small>${esc(o.date)}</small></div><div><b>${o.price} EGP</b><br><span class="status">${esc(o.status)}</span></div></div>`).join(''):'<div class="empty">Login to view your orders.</div>'}
function renderAccountButton(){$('#accountBtn').textContent=selectedUser?'Account / Logout':'Login / Sign Up'}
function openAuth(mode='login'){modal('accountModal');let signup=mode==='signup';$('#auth').innerHTML=signup?`<small>ACCOUNT</small><h2>Sign Up</h2><input id="auName" placeholder="Full name"><input id="auEmail" type="email" placeholder="Email"><input id="auPass" type="password" placeholder="Password"><button id="authSubmit" class="btn wide">Create Account</button><p class="muted">Already have an account? <a href="#" id="switchAuth">Login</a></p>`:`<small>ACCOUNT</small><h2>Login</h2><input id="auEmail" type="email" placeholder="Email"><input id="auPass" type="password" placeholder="Password"><button id="authSubmit" class="btn wide">Login</button><p class="muted">New here? <a href="#" id="switchAuth">Sign Up</a></p>`;$('#authSubmit').onclick=()=>{let email=$('#auEmail').value.trim().toLowerCase(),pass=$('#auPass').value;if(!email||!pass)return toast('Fill all required fields');if(signup){let name=$('#auName').value.trim();if(!name)return toast('Enter your name');if(data.users.some(u=>u.email===email))return toast('Email already registered');data.users.push({name,email,password:pass});selectedUser={name,email};localStorage.setItem('flash_user',JSON.stringify(selectedUser));save();modal('accountModal',false);render();toast('Account created')}else{let u=data.users.find(x=>x.email===email&&x.password===pass);if(!u)return toast('Wrong email or password');selectedUser={name:u.name,email:u.email};localStorage.setItem('flash_user',JSON.stringify(selectedUser));modal('accountModal',false);render();toast('Logged in')}};$('#switchAuth').onclick=e=>{e.preventDefault();openAuth(signup?'login':'signup')}}
$('#accountBtn').onclick=()=>{if(selectedUser){if(confirm('Logout from this account?')){selectedUser=null;localStorage.removeItem('flash_user');render();toast('Logged out')}}else openAuth('login')};
$('#adminBtn').onclick=()=>{modal('adminModal');if(localStorage.getItem('flash_admin')==='1')showPanel();else{ $('#adminLogin').classList.remove('hide');$('#panel').classList.add('hide')}};
$('#adminLoginBtn').onclick=()=>{let p=$('#adminPass').value;if(p===localStorage.getItem('flash_admin_pass')||(!localStorage.getItem('flash_admin_pass')&&p==='2013')){localStorage.setItem('flash_admin','1');showPanel()}else toast('Wrong admin password')};function showPanel(){$('#adminLogin').classList.add('hide');$('#panel').classList.remove('hide');renderAdmin('categories')}
$('#logoutAdmin').onclick=()=>{localStorage.removeItem('flash_admin');modal('adminModal',false)};document.querySelectorAll('.tabs button[data-tab]').forEach(b=>b.onclick=()=>renderAdmin(b.dataset.tab));
function renderAdmin(tab){let e=$('#adminContent');if(tab==='categories')e.innerHTML=`<h3>Categories</h3><form id="catForm" class="form"><input name="name" placeholder="Category name" required><input name="image" placeholder="Image URL" required><button class="btn wide">Add Category</button></form>${data.categories.map(c=>`<div class="row"><img src="${esc(c.image)}"><div class="grow"><b>${esc(c.name)}</b></div><button class="mini" data-editcat="${esc(c.id)}">Edit</button><button class="mini danger" data-delcat="${esc(c.id)}">Delete</button></div>`).join('')}`;
if(tab==='products')e.innerHTML=`<h3>Products</h3><form id="prodForm" class="form"><input name="name" placeholder="Product name" required><select name="cat">${data.categories.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select><input name="image" placeholder="Image URL" required><input name="price" type="number" placeholder="Price EGP" required><input name="old" type="number" placeholder="Old price (optional)"><input name="options" class="wide" placeholder="Options e.g. FULL:3400,SIGN:1650"><textarea name="desc" placeholder="Description"></textarea><button class="btn wide">Add Product</button></form>${data.products.map(p=>`<div class="row"><img src="${esc(p.image)}"><div class="grow"><b>${esc(p.name)}</b><br><small>${p.options.map(o=>o.name+':'+o.price).join(' · ')}</small></div><button class="mini" data-editprod="${esc(p.id)}">Edit</button><button class="mini danger" data-delprod="${esc(p.id)}">Delete</button></div>`).join('')}`;
if(tab==='orders')e.innerHTML=`<h3>All Orders</h3>${data.orders.length?data.orders.map(o=>`<div class="row"><div class="grow"><b>Order ${o.id} — ${esc(o.product)}</b><br>${esc(o.name)} · ${esc(o.user)} · ${esc(o.option)} · ${o.price} EGP<br><small>${esc(o.date)}</small></div><select data-status="${o.id}">${['New','Processing','Done','Cancelled'].map(s=>`<option ${o.status===s?'selected':''}>${s}</option>`).join('')}</select><button class="mini danger" data-delorder="${o.id}">Delete</button></div>`).join(''):'<div class="empty">No orders.</div>'}`;
if(tab==='settings')e.innerHTML=`<h3>Store Settings</h3><label>WhatsApp<input id="setWa" value="${esc(data.settings.whatsapp)}"></label><label>Store Name<input id="setName" value="${esc(data.settings.storeName)}"></label><label>Slogan<input id="setSlogan" value="${esc(data.settings.slogan)}"></label><button id="saveSet" class="btn">Save Settings</button><hr><h3>Change Admin Password</h3><input id="oldAdmin" type="password" placeholder="Current admin password"><input id="newAdmin" type="password" placeholder="New admin password"><button id="changeAdmin" class="btn">Change Password</button><p class="muted">First-time default password is 2013.</p>`;bindAdmin(tab)}
function bindAdmin(tab){$('#catForm')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);data.categories.push({id:crypto.randomUUID(),name:f.get('name'),image:f.get('image')});save();render();renderAdmin('categories');toast('Category added')});document.querySelectorAll('[data-delcat]').forEach(b=>b.onclick=()=>{if(confirm('Delete category and its products?')){data.categories=data.categories.filter(c=>c.id!==b.dataset.delcat);data.products=data.products.filter(p=>p.cat!==b.dataset.delcat);save();render();renderAdmin('categories')}});document.querySelectorAll('[data-editcat]').forEach(b=>b.onclick=()=>{let c=data.categories.find(x=>x.id===b.dataset.editcat);let n=prompt('Category name:',c.name);if(n===null)return;let im=prompt('Image URL:',c.image);if(im===null)return;c.name=n;c.image=im;save();render();renderAdmin('categories')});$('#prodForm')?.addEventListener('submit',e=>{e.preventDefault();let f=new FormData(e.target);let opts=(f.get('options')||('FULL:'+f.get('price'))).split(',').map(x=>{let[a,b]=x.split(':');return{name:a.trim(),price:Number(b)||0}});data.products.push({id:crypto.randomUUID(),cat:f.get('cat'),name:f.get('name'),desc:f.get('desc'),image:f.get('image'),options:opts,old:Number(f.get('old'))||0});save();render();renderAdmin('products');toast('Product added')});document.querySelectorAll('[data-delprod]').forEach(b=>b.onclick=()=>{if(confirm('Delete product?')){data.products=data.products.filter(p=>p.id!==b.dataset.delprod);save();render();renderAdmin('products')}});document.querySelectorAll('[data-editprod]').forEach(b=>b.onclick=()=>{let p=data.products.find(x=>x.id===b.dataset.editprod);let n=prompt('Product name:',p.name);if(n===null)return;let im=prompt('Image URL:',p.image);if(im===null)return;let op=prompt('Options e.g. FULL:3400,SIGN:1650:',p.options.map(o=>o.name+':'+o.price).join(','));if(op===null)return;p.name=n;p.image=im;p.options=op.split(',').map(x=>{let[a,b]=x.split(':');return{name:a.trim(),price:Number(b)||0}});save();render();renderAdmin('products')});document.querySelectorAll('[data-status]').forEach(s=>s.onchange=()=>{data.orders.find(o=>o.id==s.dataset.status).status=s.value;save();renderOrders()});document.querySelectorAll('[data-delorder]').forEach(b=>b.onclick=()=>{data.orders=data.orders.filter(o=>o.id!=b.dataset.delorder);save();renderAdmin('orders');renderOrders()});$('#saveSet')?.addEventListener('click',()=>{data.settings.whatsapp=$('#setWa').value.replace(/\D/g,'');data.settings.storeName=$('#setName').value;data.settings.slogan=$('#setSlogan').value;save();render();toast('Settings saved')});$('#changeAdmin')?.addEventListener('click',()=>{let current=localStorage.getItem('flash_admin_pass')||'2013';if($('#oldAdmin').value!==current)return toast('Current password is wrong');let n=$('#newAdmin').value;if(n.length<4)return toast('New password must be 4+ characters');localStorage.setItem('flash_admin_pass',n);toast('Admin password changed')})}
$('#back').onclick=()=>{$('#products').classList.add('hide');$('#offers').classList.remove('hide');location.hash='categories'};$('#menu').onclick=()=>toast('Use the navigation on desktop');
render();
