const state={products:[],categories:[],banners:[],featured:[],featuredIndex:0,heroIndex:0,selectedCategory:null,selectedPlatform:null,search:""};
const money=n=>`${Number(n||0).toLocaleString()} EGP`;
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const img=u=>u||"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="700"><rect width="100%" height="100%" fill="#151922"/><text x="50%" y="50%" fill="#ffb000" font-size="52" font-family="Arial" font-weight="700" text-anchor="middle">FLASH STORE</text></svg>');
function toast(x){const t=document.querySelector("#toast");t.textContent=x;t.style.display="block";clearTimeout(window._t);window._t=setTimeout(()=>t.style.display="none",2200)}
function cart(){try{return JSON.parse(localStorage.flashCart||"[]")}catch{return[]}}
function saveCart(c){localStorage.flashCart=JSON.stringify(c);const el=document.querySelector("#cartCount");if(el)el.textContent=c.reduce((a,b)=>a+b.quantity,0)}
function addCart(p,opt){const c=cart(),key=p.id+":"+(opt?.id||"");const x=c.find(i=>i.key===key);if(x)x.quantity++;else c.push({key,product_id:p.id,option_id:opt?.id||null,name:p.name,option_name:opt?.name||"",price:Number(opt?.price??p.price),image:opt?.image_url||p.image_url,quantity:1});saveCart(c);toast("Added to cart")}
function card(p){const options=p.options||[];const price=options.length?Math.min(...options.map(o=>Number(o.price))):p.price;return `<article class="product-card" onclick="location.href='/product.html?id=${encodeURIComponent(p.id)}'"><img src="${img((p.images||[])[0]||p.image_url)}" alt=""><div class="product-info">${p.discount_badge?'<span class="badge">DEAL</span>':''}<h3>${esc(p.name)}</h3><p>${esc(p.description||p.platform||"Digital product")}</p><div><span class="price">${money(price)}</span>${p.old_price>price?`<span class="old">${money(p.old_price)}</span>`:""}</div><div class="card-actions"><a class="small-btn" href="/product.html?id=${encodeURIComponent(p.id)}" onclick="event.stopPropagation()">View</a><a class="btn" href="/product.html?id=${encodeURIComponent(p.id)}" onclick="event.stopPropagation()">BUY NOW</a></div></div></article>`}
function renderHero(){const b=state.banners.filter(x=>x.active!==false);const hero=document.querySelector('#hero');const ov=document.querySelector('#heroOverlay');if(!b.length){hero.classList.add('hero-empty');document.querySelector('#heroImg').src=img('');document.querySelector('#heroTitle').textContent='FLASH STORE';document.querySelector('#heroText').textContent='Choose a category and start shopping.';document.querySelector('#heroBtn').href='#categories';document.querySelector('#heroBtn').textContent='BROWSE CATEGORIES';document.querySelector('#heroDots').innerHTML='';ov?.classList.add('hidden');return}hero.classList.remove('hero-empty');const x=b[state.heroIndex%b.length];document.querySelector('#heroImg').src=img(x.image_url);document.querySelector('#heroEyebrow').textContent='FLASH STORE';document.querySelector('#heroTitle').textContent=x.title||'Level up your gaming.';document.querySelector('#heroText').textContent=x.text||'';const btn=document.querySelector('#heroBtn');btn.textContent=x.button_text||'BUY NOW';btn.href=x.product_id?`/product.html?id=${encodeURIComponent(x.product_id)}`:'#products';document.querySelector('#heroDots').innerHTML=b.map((_,i)=>`<button class="dot ${i===state.heroIndex%b.length?'active':''}" onclick="setHero(${i})"></button>`).join('');if(ov){const product=x.product_id?state.products.find(p=>String(p.id)===String(x.product_id)):null;ov.className=`hero-overlay ${x.overlay_position||'bottom-left'} ${x.overlay_enabled?'':'hidden'}`;document.querySelector('#heroOverlayTitle').textContent=x.overlay_title||'FLASH STORE';document.querySelector('#heroOverlayText').textContent=x.overlay_text||'';document.querySelector('#heroOverlayCategory').textContent=x.overlay_show_category?(product?.category_name||product?.platform||'') : '';const price=product?.options?.length?Math.min(...product.options.map(o=>Number(o.price))):product?.price;document.querySelector('#heroOverlayPrice').textContent=x.overlay_show_price&&price?money(price):'';const ob=document.querySelector('#heroOverlayBtn');ob.textContent=x.overlay_button_text||x.button_text||'BUY NOW';ob.href=x.product_id?`/product.html?id=${encodeURIComponent(x.product_id)}`:'#products'}}
window.setHero=i=>{state.heroIndex=i;renderHero()};
function render(){
 const cats=state.categories;document.querySelector('#categoriesGrid').innerHTML=cats.map(c=>`<a class="category-card" href="/category.html?id=${encodeURIComponent(c.id)}"><div class="category-cover">${c.image_url?`<img src="${img(c.image_url)}" alt="">`:''}</div><strong>${esc(c.name)}</strong><span class="muted">${esc(c.description||'Explore category')}</span></a>`).join('')||'<p class="muted">No categories yet.</p>';
 document.querySelector('#drawerCats').innerHTML=cats.map(c=>`<a href="/category.html?id=${encodeURIComponent(c.id)}">${esc(c.name)}</a>`).join('')||'<p class="muted">No categories yet.</p>';
 let list=state.products.filter(p=>p.active!==false);if(state.selectedCategory)list=list.filter(p=>p.category_id===state.selectedCategory);if(state.selectedPlatform)list=list.filter(p=>(p.platform||'').toLowerCase()===state.selectedPlatform.toLowerCase());if(state.search)list=list.filter(p=>(p.name+' '+p.description+' '+p.platform).toLowerCase().includes(state.search.toLowerCase()));
 document.querySelector('#productsGrid').innerHTML=list.map(card).join('')||'<p class="muted">No products found.</p>';document.querySelector('#productHeading').textContent=state.search?`Search: ${state.search}`:state.selectedCategory?'Category Products':state.selectedPlatform?state.selectedPlatform+' Products':'Products';
 state.featured=state.products.filter(p=>p.featured);const max=Math.max(0,state.featured.length-4);state.featuredIndex=Math.min(state.featuredIndex,max);document.querySelector('#featuredGrid').innerHTML=state.featured.slice(state.featuredIndex,state.featuredIndex+4).map(card).join('')||'<p class="muted">Featured products will appear here.</p>';
 const cutoff=Date.now()-60*24*60*60*1000;document.querySelector('#newGrid').innerHTML=state.products.filter(p=>new Date(p.created_at).getTime()>=cutoff).map(card).join('')||'<p class="muted">No newly added products.</p>';
 const plats=[...new Set(state.products.map(p=>p.platform).filter(Boolean))];document.querySelector('#platformGrid').innerHTML=plats.map(x=>`<button class="platform-card" onclick="filterPlatform('${esc(x)}')"><div class="platform-icon">${esc(x)}</div><strong>${esc(x)}</strong><span class="muted">View products</span></button>`).join('')||'<p class="muted">Platforms appear as products are added.</p>';renderHero();
}
window.filterPlatform=x=>{state.selectedPlatform=x;state.selectedCategory=null;render();document.querySelector('#products').scrollIntoView({behavior:'smooth'})};
async function load(){try{const r=await fetch('/api/store');const d=await r.json();if(!r.ok)throw Error(d.error||'Store data could not load');state.categories=d.categories||[];state.products=(d.products||[]).map(p=>({...p,category_name:(d.categories||[]).find(c=>String(c.id)===String(p.category_id))?.name||''}));state.banners=d.banners||[];const s=d.settings?.[0];if(s){document.title=s.store_name||'FLASH STORE';document.querySelector('#aboutText').textContent=s.about_text||'';document.querySelector('#supportTitle').textContent=s.support_title||'Support';document.querySelector('#supportText').textContent=s.support_text||'Need help? Contact us on WhatsApp.';const wa=String(s.whatsapp||'').replace(/[^0-9]/g,'');const sb=document.querySelector('#supportBtn');if(sb)sb.href=wa?`https://wa.me/${wa}`:'#'}render()}catch(e){toast(e.message||'Store data could not load');console.error(e)}}
document.querySelector('#search').oninput=e=>{state.search=e.target.value;render()};document.querySelector('#prevFeatured').onclick=()=>{state.featuredIndex=Math.max(0,state.featuredIndex-1);render()};document.querySelector('#nextFeatured').onclick=()=>{state.featuredIndex=Math.min(Math.max(0,state.featured.length-4),state.featuredIndex+1);render()};document.querySelector('#heroPrev').onclick=()=>{if(state.banners.length)state.heroIndex=(state.heroIndex-1+state.banners.length)%state.banners.length;renderHero()};document.querySelector('#heroNext').onclick=()=>{if(state.banners.length)state.heroIndex=(state.heroIndex+1)%state.banners.length;renderHero()};document.querySelector('#menuBtn').onclick=()=>document.querySelector('#drawer').classList.add('open');document.querySelector('#closeDrawer').onclick=()=>document.querySelector('#drawer').classList.remove('open');saveCart(cart());load();setInterval(()=>{if(state.banners.length){state.heroIndex=(state.heroIndex+1)%state.banners.length;renderHero()}},5000);
