let items=[],payments=[],discountAmount=0,currentUser=null,requiresAccount=false;
const money=n=>`${Number(n||0).toLocaleString()} EGP`,esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function cart(){try{return JSON.parse(localStorage.flashCart||"[]")}catch{return[]}}
function saveCart(c){items=c;localStorage.flashCart=JSON.stringify(c);renderCart()}
function totals(){const sub=items.reduce((a,x)=>a+Number(x.price)*Number(x.quantity||1),0);document.querySelector("#sub").textContent=money(sub);document.querySelector("#disc").textContent=money(discountAmount);document.querySelector("#total").textContent=money(Math.max(0,sub-discountAmount))}
function renderCart(){document.querySelector("#items").innerHTML=items.length?items.map((x,i)=>`<div class="cart-line"><img src="${esc(x.image||'')}" alt=""><div><b>${esc(x.name)}</b><div class="muted">${x.option_name?esc(x.option_name)+' · ':''}${money(x.price)}</div></div><div class="cart-qty"><button class="small-btn" onclick="changeQty(${i},-1)">−</button><b>${x.quantity}</b><button class="small-btn" onclick="changeQty(${i},1)">+</button></div><div class="cart-price"><b>${money(x.price*x.quantity)}</b><button class="small-btn remove-cart" onclick="removeItem(${i})">Remove</button></div></div>`).join(""):"<p class='muted'>Your cart is empty.</p>";document.querySelector('#place').disabled=!items.length;totals()}
window.changeQty=(i,d)=>{items[i].quantity=Math.max(1,Number(items[i].quantity||1)+d);saveCart(items)};window.removeItem=i=>{items.splice(i,1);saveCart(items)};
async function init(){items=cart();renderCart();if(!items.length)return;const me=await fetch('/api/me').then(r=>r.ok?r.json():null).catch(()=>null);if(!me){document.querySelector('#authGate').classList.remove('hidden');return}currentUser=me;document.querySelector('#checkoutWrap').classList.remove('hidden');document.querySelector('#fullName').value=me.full_name||'';document.querySelector('#email').value=me.email||'';const store=await fetch('/api/store').then(r=>r.json());payments=store.payments||[];const products=store.products||[];const productMap=new Map(products.map(p=>[String(p.id),p]));requiresAccount=items.some(i=>productMap.get(String(i.product_id))?.requires_account_details);if(requiresAccount)document.querySelector('#accountFields').classList.remove('hidden');document.querySelector('#payment').innerHTML=payments.map(p=>`<option value="${esc(p.name)}">${esc(p.name)}</option>`).join('');updatePayment();renderCart()}
function updatePayment(){const p=payments.find(x=>x.name===document.querySelector('#payment').value);document.querySelector('#paymentDetails').textContent=p?p.details:""}
document.querySelector('#payment').onchange=updatePayment;document.querySelector('#proof').onchange=e=>{const f=e.target.files[0],im=document.querySelector('#proofPreview');if(f){im.src=URL.createObjectURL(f);im.style.display='block'}else im.style.display='none'};
document.querySelector('#apply').onclick=async()=>{const code=document.querySelector('#discount').value.trim();if(!code)return;const r=await fetch('/api/discount',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,items})});const d=await r.json();if(!r.ok){document.querySelector('#discountMsg').textContent=d.error||'Invalid code';discountAmount=0}else{discountAmount=Number(d.amount||0);document.querySelector('#discountMsg').textContent=`Applied: ${d.label||code}`}totals()};
document.querySelector('#place').onclick=async()=>{if(!items.length)return;if(!currentUser){location.href='/account.html?return=/checkout.html';return}if(!document.querySelector('#fullName').value.trim()||!document.querySelector('#phone').value.trim()){document.querySelector('#checkoutMsg').textContent='Please complete your name and phone.';return}if(requiresAccount&&(!document.querySelector('#accountEmail').value.trim()||!document.querySelector('#accountPassword').value)){document.querySelector('#checkoutMsg').textContent='This order requires the product Email and Password.';return}const file=document.querySelector('#proof').files[0];if(!file){document.querySelector('#checkoutMsg').textContent='Payment proof is required.';return}document.querySelector('#place').disabled=true;document.querySelector('#checkoutMsg').textContent='Uploading payment proof...';try{const fd=new FormData();fd.append('proof',file);const up=await fetch('/api/upload-proof',{method:'POST',body:fd});const ud=await up.json();if(!up.ok)throw Error(ud.error||'Payment proof upload failed');document.querySelector('#checkoutMsg').textContent='Placing order...';const payload={full_name:document.querySelector('#fullName').value.trim(),phone:document.querySelector('#phone').value.trim(),payment_method:document.querySelector('#payment').value,items,discount_code:document.querySelector('#discount').value.trim(),proof_url:ud.url,account_email:requiresAccount?document.querySelector('#accountEmail').value.trim():'',account_password:requiresAccount?document.querySelector('#accountPassword').value:''};const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not place order');localStorage.removeItem('flashCart');document.querySelector('main').innerHTML=`<section class="modal-box" style="max-width:700px;margin:70px auto;text-align:center"><div style="font-size:70px">✓</div><span class="eyebrow">ORDER RECEIVED</span><h1>Order #${d.order_number}</h1><p class="muted">Your payment proof was received. FLASH STORE will contact you to confirm the order.</p><a class="btn" href="/">Back to Store</a></section>`}catch(e){document.querySelector('#checkoutMsg').textContent=e.message;document.querySelector('#place').disabled=false}};
init();
