-- FLASH STORE V16 CLEAN
-- Run once in a fresh/empty Supabase project.
-- IMPORTANT: Service Role key stays server-side only.

create table if not exists public.store_settings(
 id bigint primary key default 1,
 store_name text not null default 'FLASH STORE',
 tagline text default 'Gaming & Digital Store',
 whatsapp text default '',
 discord text default '',
 instapay text default '',
 telda text default '',
 vodafone_cash text default '',
 announcement text default 'FLASH STORE',
 hero_title text default 'FLASH STORE',
 hero_text text default 'Gaming & digital products.',
 currency text not null default 'EGP',
 updated_at timestamptz not null default now()
);

create table if not exists public.categories(
 id bigint generated by default as identity primary key,
 name text not null unique,
 description text default '',
 image text default '',
 active boolean not null default true,
 show_on_home boolean not null default true,
 sort_order integer not null default 0,
 created_at timestamptz not null default now()
);

create table if not exists public.products(
 id bigint generated by default as identity primary key,
 name text not null,
 price numeric(12,2) not null default 0,
 category_id bigint references public.categories(id) on delete set null,
 platform text default 'Other',
 description text default '',
 image text default '',
 emoji text default '🎮',
 active boolean not null default true,
 featured boolean not null default false,
 sales_count integer not null default 0,
 options jsonb not null default '[]'::jsonb,
 requires_email boolean not null default false,
 requires_password boolean not null default false,
 created_at timestamptz not null default now()
);

create table if not exists public.users(
 id bigint generated by default as identity primary key,
 email text not null unique,
 name text not null,
 phone text default '',
 password_hash text not null,
 role text not null default 'client' check(role in('admin','client')),
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.discounts(
 id bigint generated by default as identity primary key,
 code text not null unique,
 type text not null default 'percent' check(type in('percent','fixed')),
 value numeric(12,2) not null default 0,
 active boolean not null default true,
 min_total numeric(12,2) not null default 0,
 max_uses integer not null default 0,
 used_count integer not null default 0,
 first_order_only boolean not null default false,
 created_at timestamptz not null default now()
);

-- NEW: exact products a discount applies to.
create table if not exists public.discount_products(
 discount_id bigint not null references public.discounts(id) on delete cascade,
 product_id bigint not null references public.products(id) on delete cascade,
 primary key(discount_id,product_id)
);

-- NEW: exact categories a discount applies to.
create table if not exists public.discount_categories(
 discount_id bigint not null references public.discounts(id) on delete cascade,
 category_id bigint not null references public.categories(id) on delete cascade,
 primary key(discount_id,category_id)
);

create table if not exists public.orders(
 id bigint generated by default as identity primary key,
 order_number bigint not null unique,
 user_id bigint references public.users(id) on delete set null,
 full_name text not null,
 phone text not null,
 email text not null,
 payment_method text not null,
 payment_reference text default '',
 payment_proof_url text default '',
 items jsonb not null default '[]'::jsonb,
 subtotal numeric(12,2) not null default 0,
 discount numeric(12,2) not null default 0,
 total numeric(12,2) not null default 0,
 status text not null default 'new',
 created_at timestamptz not null default now()
);

create sequence if not exists public.order_number_seq start 1001;

insert into public.store_settings(id,store_name,tagline,currency)
values(1,'FLASH STORE','Gaming & Digital Store','EGP')
on conflict(id) do nothing;

alter table public.store_settings enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.users enable row level security;
alter table public.discounts enable row level security;
alter table public.discount_products enable row level security;
alter table public.discount_categories enable row level security;
alter table public.orders enable row level security;

drop policy if exists "public settings read" on public.store_settings;
create policy "public settings read" on public.store_settings for select using(true);

drop policy if exists "public categories read" on public.categories;
create policy "public categories read" on public.categories for select using(active=true);

drop policy if exists "public products read" on public.products;
create policy "public products read" on public.products for select using(active=true);

insert into public.categories(name,description,sort_order) values
('Xbox','Xbox games, accounts and subscriptions',1),
('PlayStation','PlayStation games and subscriptions',2),
('Steam','Steam games and digital products',3),
('Fortnite','V-Bucks and Fortnite products',4),
('Gift Cards','Digital gift cards',5)
on conflict(name) do nothing;
