-- FLASH STORE V15 database setup
-- Run this once in Supabase SQL Editor.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  image text default '',
  active boolean not null default true,
  show_on_home boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric not null default 0,
  category text not null default 'Other',
  description text default '',
  image text default '',
  emoji text default '🎮',
  active boolean not null default true,
  discount_active boolean not null default false,
  discount_type text not null default 'percent',
  discount_value numeric not null default 0,
  options jsonb not null default '[]'::jsonb,
  show_on_discounts boolean not null default false,
  show_on_flash boolean not null default false,
  show_on_best_sellers boolean not null default false,
  sales_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_discounts (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete cascade,
  name text default '',
  type text not null default 'percent',
  value numeric not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id bigint generated by default as identity primary key,
  "storeName" text default 'FLASH STORE',
  tagline text default 'Gaming & Digital Store',
  whatsapp text default '',
  discord text default '',
  instapay text default '',
  telda text default '',
  vodafone_cash text default '',
  currency text default 'EGP',
  announcement text default '⚡ FLASH STORE',
  "heroTitle" text default 'FLASH STORE',
  "heroText" text default 'Gaming & digital products.',
  "googleClientId" text default '',
  next_order_number bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text not null,
  phone text not null,
  password_hash text not null,
  password_salt text not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id text primary key,
  order_number bigint unique not null,
  name text not null,
  phone text not null,
  discord text not null,
  payment text not null,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric not null default 0,
  discount numeric not null default 0,
  total numeric not null default 0,
  coupon text default '',
  user_id bigint references public.users(id) on delete set null,
  user_email text default '',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.discounts (
  id bigint generated by default as identity primary key,
  code text unique not null,
  type text not null default 'percent',
  value numeric not null default 0,
  min_total numeric not null default 0,
  active boolean not null default true,
  first_order_only boolean not null default false,
  max_uses integer not null default 0,
  used_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.discount_usages (
  id bigint generated by default as identity primary key,
  discount_id bigint not null references public.discounts(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  order_id text references public.orders(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(discount_id,user_id)
);

-- Add any V15 columns to tables created by an older version.
alter table public.categories add column if not exists show_on_home boolean not null default true;
alter table public.categories add column if not exists sort_order integer not null default 0;
alter table public.categories add column if not exists created_at timestamptz not null default now();
alter table public.products add column if not exists discount_active boolean not null default false;
alter table public.products add column if not exists discount_type text not null default 'percent';
alter table public.products add column if not exists discount_value numeric not null default 0;
alter table public.products add column if not exists options jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists show_on_discounts boolean not null default false;
alter table public.products add column if not exists show_on_flash boolean not null default false;
alter table public.products add column if not exists show_on_best_sellers boolean not null default false;
alter table public.products add column if not exists sales_count integer not null default 0;
alter table public.products add column if not exists created_at timestamptz not null default now();
alter table public.store_settings add column if not exists vodafone_cash text default '';
alter table public.store_settings add column if not exists next_order_number bigint not null default 0;
alter table public.store_settings add column if not exists store_name text default 'FLASH STORE';
alter table public.store_settings add column if not exists hero_title text default 'FLASH STORE';
alter table public.store_settings add column if not exists hero_text text default 'Gaming & digital products.';
alter table public.store_settings add column if not exists google_client_id text default '';

-- Public read policies. These are safe because only active catalog/settings are public.
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_discounts enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists "Public can view active categories" on public.categories;
drop policy if exists "Public can view active products" on public.products;
drop policy if exists "Public can view active product discounts" on public.product_discounts;
drop policy if exists "Public can view store settings" on public.store_settings;
create policy "Public can view active categories" on public.categories for select to anon, authenticated using (active = true);
create policy "Public can view active products" on public.products for select to anon, authenticated using (active = true);
create policy "Public can view active product discounts" on public.product_discounts for select to anon, authenticated using (active = true);
create policy "Public can view store settings" on public.store_settings for select to anon, authenticated using (true);

-- Seed the first settings row only when the table is empty.
insert into public.store_settings ("storeName",tagline,whatsapp,discord,instapay,telda,vodafone_cash,currency,announcement,"heroTitle","heroText")
select 'FLASH STORE','Gaming & Digital Store','201000000000','FLASH STORE','InstaPay','Telda','Vodafone Cash','EGP','⚡ FLASH STORE | Fast gaming & digital products','FLASH STORE','Gaming & digital products with fast support.'
where not exists (select 1 from public.store_settings);

-- Seed starter categories/products only if the tables are empty.
insert into public.categories (name,description,active,show_on_home,sort_order)
select * from (values
 ('Fortnite','V-Bucks, subscriptions and Fortnite products',true,true,1),
 ('FIFA','FIFA products and offers',true,true,2),
 ('Gift Cards','Digital gift cards',true,true,3)
) v(name,description,active,show_on_home,sort_order)
where not exists (select 1 from public.categories);

insert into public.products (name,price,category,description,emoji,active)
select * from (values
 ('800 V-Bucks',400,'Fortnite','Digital V-Bucks package','🎮',true),
 ('2,400 V-Bucks',700,'Fortnite','Digital V-Bucks package','🪙',true),
 ('4,500 V-Bucks',1150,'Fortnite','Digital V-Bucks package','⚡',true),
 ('12,000 V-Bucks',2300,'Fortnite','Digital V-Bucks package','💎',true),
 ('Fortnite Crew',200,'Fortnite','Fortnite Crew subscription','👑',true)
) v(name,price,category,description,emoji,active)
where not exists (select 1 from public.products);

insert into public.discounts (code,type,value,active)
select 'FLASH10','percent',10,true
where not exists (select 1 from public.discounts where code='FLASH10');
