-- FLASH STORE V15
-- Safe migration: uses fs_* tables, so it does NOT delete your old V14/V15 tables.
-- Run this whole file once in Supabase SQL Editor.

create table if not exists public.fs_settings (
  id bigint primary key default 1,
  store_name text not null default 'FLASH STORE',
  tagline text default 'Gaming & Digital Store',
  whatsapp text default '',
  discord text default '',
  instapay text default '',
  telda text default '',
  vodafone_cash text default '',
  currency text default 'EGP',
  announcement text default '⚡ FLASH STORE',
  hero_title text default 'FLASH STORE',
  hero_text text default 'Gaming & digital products.',
  google_client_id text default '',
  next_order_number bigint not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.fs_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text default '',
  image text default '',
  active boolean not null default true,
  show_on_home boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.fs_products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  category text not null default 'Other',
  description text default '',
  image text default '',
  emoji text default '🎮',
  active boolean not null default true,
  discount_active boolean not null default false,
  discount_type text not null default 'percent',
  discount_value numeric(12,2) not null default 0,
  options jsonb not null default '[]'::jsonb,
  show_on_discounts boolean not null default false,
  show_on_flash boolean not null default false,
  show_on_best_sellers boolean not null default false,
  sales_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.fs_users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text not null,
  phone text not null,
  password_hash text not null,
  password_salt text not null,
  status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.fs_discounts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  type text not null default 'percent',
  value numeric(12,2) not null default 0,
  min_total numeric(12,2) not null default 0,
  active boolean not null default true,
  first_order_only boolean not null default false,
  max_uses integer not null default 0,
  used_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.fs_orders (
  id bigint generated by default as identity primary key,
  order_number bigint not null unique,
  name text not null,
  phone text not null,
  discord text not null,
  payment text not null,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  coupon text default '',
  user_id bigint,
  user_email text default '',
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.fs_discount_usages (
  id bigint generated by default as identity primary key,
  discount_id bigint not null references public.fs_discounts(id) on delete cascade,
  user_id bigint not null references public.fs_users(id) on delete cascade,
  order_id bigint references public.fs_orders(id) on delete set null,
  used_at timestamptz not null default now(),
  unique(discount_id,user_id)
);

-- Add columns if an earlier fs_* table already existed.
alter table public.fs_settings add column if not exists vodafone_cash text default '';
alter table public.fs_products add column if not exists options jsonb not null default '[]'::jsonb;
alter table public.fs_products add column if not exists show_on_discounts boolean not null default false;
alter table public.fs_products add column if not exists show_on_flash boolean not null default false;
alter table public.fs_products add column if not exists show_on_best_sellers boolean not null default false;
alter table public.fs_products add column if not exists sales_count integer not null default 0;
alter table public.fs_discounts add column if not exists first_order_only boolean not null default false;
alter table public.fs_discounts add column if not exists max_uses integer not null default 0;
alter table public.fs_discounts add column if not exists used_count integer not null default 0;

-- One starter settings row.
insert into public.fs_settings (id,store_name,tagline,currency)
values (1,'FLASH STORE','Gaming & Digital Store','EGP')
on conflict (id) do nothing;

-- Starter categories/products/discounts are inserted only if the fs_* tables are empty.
insert into public.fs_categories (id,name,description,active,show_on_home,sort_order)
select v.id,v.name,v.description,true,true,v.sort_order
from (values
  (1,'Fortnite','V-Bucks, subscriptions and Fortnite products',0),
  (2,'FIFA','FIFA products and offers',1),
  (3,'Gift Cards','Digital gift cards',2)
) as v(id,name,description,sort_order)
where not exists (select 1 from public.fs_categories);

insert into public.fs_products (id,name,price,category,description,emoji,active)
select v.id,v.name,v.price,v.category,v.description,v.emoji,true
from (values
  (1,'800 V-Bucks',400,'Fortnite','Digital V-Bucks package','🎮'),
  (2,'2,400 V-Bucks',700,'Fortnite','Digital V-Bucks package','🪙'),
  (3,'4,500 V-Bucks',1150,'Fortnite','Digital V-Bucks package','⚡'),
  (4,'12,000 V-Bucks',2300,'Fortnite','Digital V-Bucks package','💎'),
  (5,'Fortnite Crew',200,'Fortnite','Fortnite Crew subscription','👑')
) as v(id,name,price,category,description,emoji)
where not exists (select 1 from public.fs_products);

insert into public.fs_discounts (code,type,value,active)
values ('FLASH10','percent',10,true)
on conflict (code) do nothing;

-- Keep the Data API locked down. The server uses the Service Role key.
alter table public.fs_settings enable row level security;
alter table public.fs_categories enable row level security;
alter table public.fs_products enable row level security;
alter table public.fs_users enable row level security;
alter table public.fs_discounts enable row level security;
alter table public.fs_orders enable row level security;
alter table public.fs_discount_usages enable row level security;
