const fs=require('fs'),path=require('path'),crypto=require('crypto');
const DATA=path.join(process.cwd(),'data'); const SECRET=process.env.FLASH_SECRET||'flash-store-v11-change-me';
const read=(n,d)=>{try{return JSON.parse(fs.readFileSync(path.join(DATA,n),'utf8'))}catch{return d}};
function json(res,status,data){res.status(status).setHeader('Content-Type','application/json; charset=utf-8').setHeader('Cache-Control','no-store').end(JSON.stringify(data));}
function sign(v){return crypto.createHmac('sha256',SECRET).update(v).digest('hex')}
function token(user){const payload=Buffer.from(JSON.stringify({id:user.id,email:user.email,name:user.name,phone:user.phone,exp:Date.now()+30*24*60*60*1000})).toString('base64url');return `u.${payload}.${sign(payload)}`}
module.exports=async(req,res)=>{try{if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});const b=typeof req.body==='object'&&req.body?req.body:await new Promise((resolve,reject)=>{let s='';req.on('data',c=>s+=c);req.on('end',()=>{try{resolve(JSON.parse(s||'{}'))}catch(e){reject(e)}});req.on('error',reject)});const email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),phone=String(b.phone||'').trim(),password=String(b.password||'');if(!name||!email||!phone||password.length<6)return json(res,400,{error:'الاسم والإيميل والواتساب وكلمة مرور 6 أحرف على الأقل مطلوبة'});const users=read('users.json',[]);if(users.some(x=>String(x.email).toLowerCase()===email))return json(res,409,{error:'هذا الإيميل مسجل بالفعل'});const salt=crypto.randomBytes(16).toString('hex'),hash=crypto.scryptSync(password,salt,64).toString('hex');const user={id:Date.now(),email,name,phone,passwordHash:hash,passwordSalt:salt,createdAt:new Date().toISOString(),status:'active'};
// Vercel deployments are read-only, so we cannot persist a new account here.
// Return a signed session for this browser; the client keeps the account locally.
const safe={id:user.id,email:user.email,name:user.name,phone:user.phone};return json(res,200,{token:token(safe),user:safe,localAccount:{email,passwordHash:hash,passwordSalt:salt,...safe}})}catch(e){console.error('AUTH REGISTER',e);return json(res,500,{error:'حدث خطأ في إنشاء الحساب: '+e.message})}};
