const {json,env,supabase}=require("./_lib");
async function getUser(req){const c=req.headers.cookie||"";const m=c.match(/(?:^|;\s*)flash_token=([^;]+)/);if(!m)return null;const root=env("SUPABASE_URL").replace(/\/rest\/v1\/?$/,"");const r=await fetch(root+"/auth/v1/user",{headers:{"apikey":env("SUPABASE_ANON_KEY"),"Authorization":"Bearer "+m[1]}});return r.ok?await r.json():null}
module.exports=async(req,res)=>{try{const u=await getUser(req);if(!u)return json(res,401,{error:"Sign in required"});const db=supabase();const prof=await db.from("profiles").select("*");const p=(prof.data||[]).find(x=>x.id===u.id);if(!p||p.role!=="admin")return json(res,403,{error:"Admin access required"});
if(req.method==="GET"){const [c,pr,d,pay,o]=await Promise.all([db.from("categories").select("*"),db.from("products").select("*"),db.from("discounts").select("*"),db.from("payment_methods").select("*"),db.from("orders").select("*")]);return json(res,200,{categories:c.data||[],products:pr.data||[],discounts:d.data||[],payments:pay.data||[],orders:(o.data||[]).sort((a,b)=>Number(b.order_number)-Number(a.order_number))})}
const b=req.body||{};
if(req.method==="POST"){if(b.type==="category"){const slug=b.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+Date.now();const q=await db.from("categories").insert({name:b.name,slug,description:b.description||""});if(q.error)throw q.error}
if(b.type==="product"){const slug=(b.name||"product").toLowerCase().replace(/[^a-z0-9]+/g,"-")+"-"+Date.now();const row={category_id:b.category_id||null,name:b.name,slug,description:b.description||"",image_url:b.image_url||"",platform:b.platform||"",old_price:Number(b.old_price||0),price:Number(b.price||0),featured:!!b.featured,best_seller:!!b.best_seller,discount_badge:!!b.discount_badge,active:b.active!==false};let q;if(b.id)q=await db.from("products").update(row,{id:"eq."+b.id});else q=await db.from("products").insert(row);if(q.error)throw q.error}
if(b.type==="discount"){const q=await db.from("discounts").insert({code:b.code,value:Number(b.value),kind:b.kind||"percent",scope:b.scope||"all",active:true});if(q.error)throw q.error;const d=q.data?.[0];if(d&&b.scope==="products")for(const id of b.product_ids||[])await db.from("discount_products").insert({discount_id:d.id,product_id:id});if(d&&b.scope==="categories")for(const id of b.category_ids||[])await db.from("discount_categories").insert({discount_id:d.id,category_id:id})}
return json(res,200,{ok:true})}
if(req.method==="DELETE"){if(!["categories","products","discounts"].includes(b.table))return json(res,400,{error:"Invalid table"});const q=await db.from(b.table).delete({id:"eq."+b.id});if(q.error)throw q.error;return json(res,200,{ok:true})}
if(req.method==="PATCH"){if(b.type==="payment"){const q=await db.from("payment_methods").update({details:b.details},{id:"eq."+b.id});if(q.error)throw q.error}if(b.type==="order"){const q=await db.from("orders").update({status:b.status},{id:"eq."+b.id});if(q.error)throw q.error}return json(res,200,{ok:true})}
json(res,405,{error:"Method not allowed"})}catch(e){json(res,500,{error:e.message})}};