const {json,env,supabase}=require("./_lib");async function getUser(req){const c=req.headers.cookie||"";const m=c.match(/(?:^|;\s*)flash_token=([^;]+)/);if(!m)return null;const r=await fetch(env("SUPABASE_URL").replace(/\/rest\/v1\/?$/,"" )+"/auth/v1/user",{headers:{apikey:env("SUPABASE_ANON_KEY"),Authorization:"Bearer "+m[1]}});return r.ok?await r.json():null} const slugify=x=>String(x||"item").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
module.exports=async(req,res)=>{try{const u=await getUser(req);if(!u)return json(res,401,{error:"Sign in required"});const db=supabase();const prof=await db.from("profiles").select("*");const p=(prof.data||[]).find(x=>x.id===u.id);if(!p||p.role!=="admin")return json(res,403,{error:"Admin access required"});let b=req.body||{};
if(req.method==="GET"){const [c,pr,d,pay,o,ban,opt]=await Promise.all([db.from("categories").select("*"),db.from("products").select("*"),db.from("discounts").select("*"),db.from("payment_methods").select("*"),db.from("orders").select("*"),db.from("hero_banners").select("*"),db.from("product_options").select("*")]);const profs=await db.from("profiles").select("*");if(profs.error)throw profs.error;return json(res,200,{categories:c.data||[],products:pr.data||[],discounts:d.data||[],payments:pay.data||[],orders:(o.data||[]).sort((a,b)=>Number(b.order_number)-Number(a.order_number)),banners:ban.data||[],options:opt.data||[],profiles:profs.data||[]})}
if(req.method==="POST"){if(b.type==="category"){const row={name:b.name,description:b.description||"",image_url:b.image_url||"",sort_order:Number(b.sort_order||0),active:b.active!==false};const q=b.id?await db.from("categories").update(row,{id:"eq."+b.id}):await db.from("categories").insert({...row,slug:slugify(b.name)+"-"+Date.now()});if(q.error)throw q.error}
else if(b.type==="product"){const row={category_id:b.category_id||null,name:b.name,slug:slugify(b.name)+"-"+Date.now(),description:b.description||"",image_url:b.image_url||"",platform:b.platform||"",old_price:Number(b.old_price||0),price:Number(b.price||0),featured:!!b.featured,best_seller:!!b.best_seller,discount_badge:!!b.discount_badge,active:b.active!==false};const q=b.id?await db.from("products").update(row,{id:"eq."+b.id}):await db.from("products").insert(row);if(q.error)throw q.error;if(b.id&&Array.isArray(b.options)){await db.from("product_options").delete({product_id:"eq."+b.id});for(const o of b.options)await db.from("product_options").insert({product_id:b.id,name:o.name,price:Number(o.price||0),old_price:Number(o.old_price||0),image_url:o.image_url||"",active:o.active!==false,sort_order:Number(o.sort_order||0)})}}
else if(b.type==="option"){const q=await db.from("product_options").insert({product_id:b.product_id,name:b.name,price:Number(b.price||0),old_price:Number(b.old_price||0),image_url:b.image_url||"",active:true,sort_order:Number(b.sort_order||0)});if(q.error)throw q.error}
else if(b.type==="admin_role"){const q=await db.from("profiles").update({role:b.role==="admin"?"admin":"client"},{email:"eq."+String(b.email||"")});if(q.error)throw q.error}
else if(b.type==="discount_update"){const q=await db.from("discounts").update({active:b.active!==false},{id:"eq."+b.id});if(q.error)throw q.error}
else if(b.type==="payment"){const q=b.id?await db.from("payment_methods").update({name:b.name,details:b.details||"",active:b.active!==false,sort_order:Number(b.sort_order||0)},{id:"eq."+b.id}):await db.from("payment_methods").insert({name:b.name,details:b.details||"",active:true,sort_order:Number(b.sort_order||0)});if(q.error)throw q.error}
else if(b.type==="banner"){const q=b.id?await db.from("hero_banners").update({title:b.title||"",text:b.text||"",image_url:b.image_url||"",button_text:b.button_text||"BUY NOW",product_id:b.product_id||null,active:b.active!==false,sort_order:Number(b.sort_order||0)},{id:"eq."+b.id}):await db.from("hero_banners").insert({title:b.title||"",text:b.text||"",image_url:b.image_url||"",button_text:b.button_text||"BUY NOW",product_id:b.product_id||null,active:true,sort_order:Number(b.sort_order||0)});if(q.error)throw q.error}
else if(b.type==="settings"){const q=await db.from("store_settings").update({store_name:b.store_name||"FLASH STORE",logo_url:b.logo_url||"",about_title:b.about_title||"About FLASH STORE",about_text:b.about_text||"",whatsapp:b.whatsapp||"",updated_at:new Date().toISOString()},{id:"eq.1"});if(q.error)throw q.error}
else if(b.type==="discount"){const q=await db.from("discounts").insert({code:b.code,value:Number(b.value),kind:b.kind||"percent",scope:b.scope||"all",first_order_only:!!b.first_order_only,one_use_per_user:!!b.one_use_per_user,max_uses:b.max_uses?Number(b.max_uses):null,active:true});if(q.error)throw q.error}
return json(res,200,{ok:true})}
if(req.method==="DELETE"){const allowed=["categories","products","discounts","payment_methods","hero_banners","product_options"];if(!allowed.includes(b.table))return json(res,400,{error:"Invalid table"});const q=await db.from(b.table).delete({id:"eq."+b.id});if(q.error)throw q.error;return json(res,200,{ok:true})}
if(req.method==="PATCH"){if(b.type==="order"){const q=await db.from("orders").update({status:b.status},{id:"eq."+b.id});if(q.error)throw q.error}return json(res,200,{ok:true})} return json(res,405,{error:"Method not allowed"})}catch(e){json(res,500,{error:e.message})}};