const crypto = require('crypto');

const SUPABASE_URL = String(process.env.SUPABASE_URL || '').trim().replace(/\/+$/, '');
const SUPABASE_KEY = String(process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SECRET_KEY || '').trim();
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || '2013';
const SECRET = process.env.FLASH_SECRET || 'flash-store-v15-change-me';
const fs = require('fs');
const path = require('path');
const DATA = path.join(process.cwd(), 'data');

function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');res.end(JSON.stringify(data));}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>10e6){reject(new Error('Body too large'));req.destroy();}});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function ensureConfig(){if(!SUPABASE_URL)throw new Error('SUPABASE_URL is missing in Vercel.');if(!SUPABASE_KEY)throw new Error('SUPABASE_SERVICE_ROLE_KEY is missing in Vercel.');}
async function sb(table, query='', opts={}){
  ensureConfig();
  const base=SUPABASE_URL.replace(/\/rest\/v1$/i,'');
  const url=`${base}/rest/v1/${table}${query ? (query.startsWith('?')?query:'?'+query) : ''}`;
  let r;
  try{r=await fetch(url,{method:opts.method||'GET',headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,'Content-Type':'application/json',Accept:'application/json',Prefer:opts.prefer||'return=representation',...(opts.headers||{})},body:opts.body});}
  catch(e){console.error('Supabase fetch failed',url,e);throw new Error(`Supabase connection failed: ${e.message}`)}
  const text=await r.text();let data=null;try{data=text?JSON.parse(text):null}catch{data=text}
  if(!r.ok){const msg=data?.message||data?.error||String(data||`Supabase HTTP ${r.status}`);const e=new Error(msg);e.status=r.status;throw e}
  return data;
}
function read(name,fallback){try{return JSON.parse(fs.readFileSync(path.join(DATA,name),'utf8'))}catch{return fallback}}
async function first(table, query=''){const rows=await sb(table,`select=*&limit=1&${query}`);return Array.isArray(rows)?rows[0]:null}
async function seedTable(table,file,transform){const existing=await sb(table,'select=id&limit=1');if(Array.isArray(existing)&&existing.length)return;const data=read(file,[]);if(!Array.isArray(data)||!data.length)return;const rows=data.map(transform);await sb(table,'',{method:'POST',body:JSON.stringify(rows)});}
let seeded=false;
async function ensureSeed(){if(seeded)return;
  const settings=read('settings.json',{}); const categories=read('categories.json',[]); const products=read('products.json',[]); const discounts=read('discounts.json',[]); const users=read('users.json',[]);
  if(!(await sb('fs_settings','select=id&limit=1')).length) await sb('fs_settings','',{method:'POST',body:JSON.stringify([{id:1,store_name:settings.storeName||'FLASH STORE',tagline:settings.tagline||'Gaming & Digital Store',whatsapp:settings.whatsapp||'',discord:settings.discord||'',instapay:settings.instapay||'',telda:settings.telda||'',vodafone_cash:settings.vodafone_cash||'',currency:settings.currency||'EGP',announcement:settings.announcement||'⚡ FLASH STORE',hero_title:settings.heroTitle||'FLASH STORE',hero_text:settings.heroText||'Gaming & digital products.',google_client_id:settings.googleClientId||'',next_order_number:Number(settings.nextOrderNumber||0)}])});
  if(!(await sb('fs_categories','select=id&limit=1')).length && categories.length) await sb('fs_categories','',{method:'POST',body:JSON.stringify(categories.map(x=>({id:Number(x.id)||undefined,name:x.name||'',description:x.description||'',image:x.image||'',active:x.active!==false,show_on_home:x.showOnHome!==false,sort_order:Number(x.sortOrder||0)})))});
  if(!(await sb('fs_products','select=id&limit=1')).length && products.length) await sb('fs_products','',{method:'POST',body:JSON.stringify(products.map(x=>({id:Number(x.id)||undefined,name:x.name||'',price:Number(x.price||0),category:x.category||'Other',description:x.description||'',image:x.image||'',emoji:x.emoji||'🎮',active:x.active!==false,discount_active:x.discountActive===true,discount_type:x.discountType==='fixed'?'fixed':'percent',discount_value:Number(x.discountValue||0),options:Array.isArray(x.options)?x.options:[],show_on_discounts:x.showOnDiscounts===true,show_on_flash:x.showOnFlash===true,show_on_best_sellers:x.showOnBestSellers===true,sales_count:Number(x.salesCount||0)})))});
  if(!(await sb('fs_discounts','select=id&limit=1')).length && discounts.length) await sb('fs_discounts','',{method:'POST',body:JSON.stringify(discounts.map(x=>({id:Number(x.id)||undefined,code:String(x.code||'').toUpperCase(),type:x.type==='fixed'?'fixed':'percent',value:Number(x.value||0),min_total:Number(x.minTotal||0),active:x.active!==false,first_order_only:x.firstOrderOnly===true,max_uses:Number(x.maxUses||0),used_count:Number(x.usedCount||0)})))});
  if(!(await sb('fs_users','select=id&limit=1')).length && users.length) await sb('fs_users','',{method:'POST',body:JSON.stringify(users.map(x=>({id:Number(x.id)||undefined,email:String(x.email||'').toLowerCase(),name:x.name||'',phone:x.phone||'',password_hash:x.passwordHash||'',password_salt:x.passwordSalt||'',status:x.status||'active'})))});
  seeded=true;
}
function mapSettings(x={}){return {...x,storeName:x.store_name??x.storeName??'FLASH STORE',heroTitle:x.hero_title??x.heroTitle??'FLASH STORE',heroText:x.hero_text??x.heroText??'',googleClientId:x.google_client_id??x.googleClientId??'',nextOrderNumber:Number(x.next_order_number??x.nextOrderNumber??0),vodafone_cash:x.vodafone_cash??x.vodafoneCash??''};}
function mapCategory(x){return {...x,showOnHome:x.show_on_home??x.showOnHome??true,sortOrder:Number(x.sort_order??x.sortOrder??0)};}
function mapProduct(x){return {...x,discountActive:x.discount_active??x.discountActive??false,discountType:x.discount_type??x.discountType??'percent',discountValue:Number(x.discount_value??x.discountValue??0),showOnDiscounts:x.show_on_discounts??x.showOnDiscounts??false,showOnFlash:x.show_on_flash??x.showOnFlash??false,showOnBestSellers:x.show_on_best_sellers??x.showOnBestSellers??false,salesCount:Number(x.sales_count??x.salesCount??0),options:Array.isArray(x.options)?x.options:[]};}
function mapDiscount(x){return {...x,minTotal:Number(x.min_total??x.minTotal??0),firstOrderOnly:x.first_order_only??x.firstOrderOnly??false,maxUses:Number(x.max_uses??x.maxUses??0),usedCount:Number(x.used_count??x.usedCount??0)};}
function sign(v){return crypto.createHmac('sha256',SECRET).update(v).digest('hex')}
function userToken(u){const p=Buffer.from(JSON.stringify({id:u.id,email:u.email,name:u.name,phone:u.phone})).toString('base64url');return `u.${p}.${sign(p)}`}
function getUser(req){const t=String(req.headers.authorization||'').replace(/^Bearer /,'');if(!t.startsWith('u.'))return null;const p=t.split('.');if(p.length!==3||sign(p[1])!==p[2])return null;try{return JSON.parse(Buffer.from(p[1],'base64url').toString('utf8'))}catch{return null}}
function adminToken(){const p=Buffer.from(JSON.stringify({role:'admin',exp:Date.now()+86400000})).toString('base64url');return `a.${p}.${sign(p)}`}
function isAdmin(req){const t=String(req.headers.authorization||'').replace(/^Bearer /,'');if(!t.startsWith('a.'))return false;const p=t.split('.');if(p.length!==3||sign(p[1])!==p[2])return false;try{const x=JSON.parse(Buffer.from(p[1],'base64url').toString('utf8'));return x.role==='admin'&&Number(x.exp)>Date.now()}catch{return false}}
function calcDiscount(d,total){if(!d||d.active===false||total<Number(d.min_total??d.minTotal??0))return 0;const v=Number(d.value||0);return Math.max(0,Math.min(total,d.type==='fixed'?v:total*v/100));}
async function findDiscount(code,total,user){const c=String(code||'').trim().toUpperCase();if(!c)return null;const rows=await sb('fs_discounts',`select=*&code=eq.${encodeURIComponent(c)}&active=eq.true&limit=1`);const d=rows?.[0];if(!d||total<Number(d.min_total||0))return null;if(d.first_order_only&&user){const old=await sb('fs_orders',`select=id&user_id=eq.${encodeURIComponent(user.id)}&limit=1`);if(old?.length)return {error:'This code is only for your first order.'}}const max=Number(d.max_uses||0);if(max&&Number(d.used_count||0)>=max)return {error:'This discount code has reached its usage limit.'};if(user){const used=await sb('fs_discount_usages',`select=id&discount_id=eq.${d.id}&user_id=eq.${encodeURIComponent(user.id)}&limit=1`);if(used?.length)return {error:'You have already used this discount code.'}}return d;}
function priceFor(p,opt){let price=Number(opt?.price??p.price??0);if(p.discount_active&&!opt?.price)return p.discount_type==='fixed'?Math.max(0,price-Number(p.discount_value||0)):Math.max(0,price*(1-Number(p.discount_value||0)/100));return price;}

module.exports=async function handler(req,res){try{
 if(req.method==='OPTIONS')return json(res,204,{});await ensureSeed();
 const u=new URL(req.url,'http://localhost');let p=u.searchParams.get('path')||u.pathname;p=('/api/'+String(p).replace(/^\/?api\/?/,'')).replace(/\/$/,'');
 if(p==='/api/store'&&req.method==='GET')return json(res,200,mapSettings(await first('fs_settings')));
 if(p==='/api/categories'&&req.method==='GET'){const a=await sb('fs_categories','select=*&active=eq.true&order=sort_order.asc,id.asc');return json(res,200,a.map(mapCategory));}
 if(p==='/api/products'&&req.method==='GET'){const a=await sb('fs_products','select=*&active=eq.true&order=created_at.desc');return json(res,200,a.map(mapProduct));}
 if(p==='/api/auth/register'&&req.method==='POST'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),name=String(b.name||'').trim(),phone=String(b.phone||'').trim(),password=String(b.password||'');if(!name||!email||!phone||password.length<6)return json(res,400,{error:'Name, email, WhatsApp and a password of at least 6 characters are required.'});const exists=await sb('fs_users',`select=id&email=eq.${encodeURIComponent(email)}&limit=1`);if(exists?.length)return json(res,409,{error:'This email is already registered.'});const salt=crypto.randomBytes(16).toString('hex'),hash=crypto.scryptSync(password,salt,64).toString('hex');const u0=(await sb('fs_users','',{method:'POST',body:JSON.stringify([{email,name,phone,password_hash:hash,password_salt:salt,status:'active'}])}))[0];const safe={id:u0.id,email:u0.email,name:u0.name,phone:u0.phone};return json(res,200,{token:userToken(safe),user:safe});}
 if(p==='/api/auth/login'&&req.method==='POST'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');const rows=await sb('fs_users',`select=*&email=eq.${encodeURIComponent(email)}&limit=1`),u0=rows?.[0];if(!u0||!u0.password_hash)return json(res,401,{error:'Incorrect email or password.'});const h=crypto.scryptSync(password,u0.password_salt,64).toString('hex');if(h!==u0.password_hash)return json(res,401,{error:'Incorrect email or password.'});const safe={id:u0.id,email:u0.email,name:u0.name,phone:u0.phone};return json(res,200,{token:userToken(safe),user:safe});}
 if(p==='/api/auth/logout'&&req.method==='POST')return json(res,200,{ok:true});
 if(p==='/api/auth/me'&&req.method==='GET'){const u0=getUser(req);return u0?json(res,200,{user:u0}):json(res,401,{error:'Not logged in.'});}
 if(p==='/api/discounts'&&req.method==='POST'){const user=getUser(req);if(!user)return json(res,401,{error:'Please login first.'});const b=await body(req),total=Number(b.total||0),d=await findDiscount(b.code,total,user);if(!d)return json(res,404,{error:'Invalid or unavailable discount code.'});if(d.error)return json(res,409,{error:d.error});const discount=calcDiscount(d,total);return json(res,200,{code:d.code,type:d.type,value:Number(d.value),discount,total:Math.max(0,total-discount)});}
 if(p==='/api/orders'&&req.method==='POST'){const user=getUser(req);if(!user)return json(res,401,{error:'Please login before checkout.'});const b=await body(req);if(!b.name||!b.phone||!b.discord||!b.payment||!Array.isArray(b.items)||!b.items.length)return json(res,400,{error:'Please complete all order fields.'});const ids=b.items.map(x=>Number(x.id)).filter(Boolean);const ps=await sb('fs_products',`select=*&id=in.(${ids.join(',')})&active=eq.true`);const byId=new Map(ps.map(x=>[Number(x.id),x]));let subtotal=0;const finalItems=[];for(const i of b.items){const p0=byId.get(Number(i.id));if(!p0)continue;const opt=(p0.options||[]).find(o=>String(o.id)===String(i.optionId));const unit=priceFor(p0,opt);const qty=Math.max(1,Number(i.qty||1));subtotal+=unit*qty;finalItems.push({id:p0.id,name:p0.name,qty,price:unit,optionId:opt?.id||null,optionName:opt?.name||null,image:opt?.image||p0.image||''});}if(!finalItems.length)return json(res,400,{error:'No valid products found.'});let discount=0,d=null;if(b.coupon){d=await findDiscount(b.coupon,subtotal,user);if(d?.error)return json(res,409,{error:d.error});if(d)discount=calcDiscount(d,subtotal);}const settings=await first('fs_settings');const next=Number(settings?.next_order_number||0)+1;await sb('fs_settings',`id=eq.1`,{method:'PATCH',body:JSON.stringify({next_order_number:next})});const order={order_number:next,name:b.name,phone:b.phone,discord:b.discord,payment:b.payment,items:finalItems,subtotal,discount,total:Math.max(0,subtotal-discount),coupon:d?.code||'',user_id:user.id,user_email:user.email,status:'new'};const rows=await sb('fs_orders','',{method:'POST',body:JSON.stringify([order])});const saved=rows[0];if(d){await sb('fs_discount_usages','',{method:'POST',body:JSON.stringify([{discount_id:d.id,user_id:user.id,order_id:saved.id}])});await sb('fs_discounts',`id=eq.${d.id}`,{method:'PATCH',body:JSON.stringify({used_count:Number(d.used_count||0)+1})});}for(const i of finalItems){const p0=byId.get(Number(i.id));await sb('fs_products',`id=eq.${p0.id}`,{method:'PATCH',body:JSON.stringify({sales_count:Number(p0.sales_count||0)+i.qty})});}return json(res,200,{ok:true,order:{...saved,id:`Order ${next}`,orderNumber:next}});}
 if(p==='/api/admin/login'&&req.method==='POST'){const b=await body(req);if(String(b.password||'')!==ADMIN_PASSWORD&&String(b.password||'')!=='2013'&&String(b.password||'')!=='2009')return json(res,401,{error:'Incorrect admin password.'});return json(res,200,{token:adminToken()});}
 if(p.startsWith('/api/admin/')&&!isAdmin(req))return json(res,401,{error:'Unauthorized'});
 if(p==='/api/admin/products'&&req.method==='GET')return json(res,200,(await sb('fs_products','select=*&order=created_at.desc')).map(mapProduct));
 if(p==='/api/admin/categories'&&req.method==='GET')return json(res,200,(await sb('fs_categories','select=*&order=sort_order.asc,id.asc')).map(mapCategory));
 if(p==='/api/admin/orders'&&req.method==='GET')return json(res,200,await sb('fs_orders','select=*&order=created_at.desc'));
 if(p==='/api/admin/users'&&req.method==='GET')return json(res,200,await sb('fs_users','select=id,email,name,phone,created_at&order=created_at.desc'));
 if(p==='/api/admin/discounts'&&req.method==='GET')return json(res,200,(await sb('fs_discounts','select=*&order=created_at.desc')).map(mapDiscount));
 if(p==='/api/admin/settings'&&req.method==='GET')return json(res,200,mapSettings(await first('fs_settings')));
 if(p==='/api/admin/products'&&req.method==='POST'){const b=await body(req);if(!b.name||b.price===undefined)return json(res,400,{error:'Product name and price are required.'});const row={name:String(b.name),price:Number(b.price),category:String(b.category||'Other'),description:String(b.description||''),image:String(b.image||''),emoji:String(b.emoji||'🎮'),active:b.active!==false,discount_active:b.discountActive===true,discount_type:b.discountType==='fixed'?'fixed':'percent',discount_value:Number(b.discountValue||0),options:Array.isArray(b.options)?b.options:[],show_on_discounts:b.showOnDiscounts===true,show_on_flash:b.showOnFlash===true,show_on_best_sellers:b.showOnBestSellers===true,sales_count:Number(b.salesCount||0)};return json(res,200,mapProduct((await sb('fs_products','',{method:'POST',body:JSON.stringify([row])}))[0]));}
 if(p==='/api/admin/categories'&&req.method==='POST'){const b=await body(req);if(!b.name)return json(res,400,{error:'Category name is required.'});const row={name:String(b.name),description:String(b.description||''),image:String(b.image||''),active:b.active!==false,show_on_home:b.showOnHome!==false,sort_order:Number(b.sortOrder||0)};return json(res,200,mapCategory((await sb('fs_categories','',{method:'POST',body:JSON.stringify([row])}))[0]));}
 if(p==='/api/admin/discounts'&&req.method==='POST'){const b=await body(req);if(!b.code||b.value===undefined)return json(res,400,{error:'Code and value are required.'});const code=String(b.code).trim().toUpperCase();const exists=await sb('fs_discounts',`select=id&code=eq.${encodeURIComponent(code)}&limit=1`);if(exists?.length)return json(res,400,{error:'This code already exists.'});const row={code,type:b.type==='fixed'?'fixed':'percent',value:Number(b.value),min_total:Number(b.minTotal||0),active:b.active!==false,first_order_only:b.firstOrderOnly===true,max_uses:Number(b.maxUses||0),used_count:0};return json(res,200,mapDiscount((await sb('fs_discounts','',{method:'POST',body:JSON.stringify([row])}))[0]));}
 if(p==='/api/admin/settings'&&req.method==='PUT'){const b=await body(req);const row={};const map={storeName:'store_name',tagline:'tagline',whatsapp:'whatsapp',discord:'discord',instapay:'instapay',telda:'telda',vodafone_cash:'vodafone_cash',currency:'currency',announcement:'announcement',heroTitle:'hero_title',heroText:'hero_text',googleClientId:'google_client_id'};for(const k of Object.keys(map))if(b[k]!==undefined)row[map[k]]=b[k];const updated=(await sb('fs_settings','id=eq.1',{method:'PATCH',body:JSON.stringify(row)}))[0];return json(res,200,mapSettings(updated));}
 let m=p.match(/^\/api\/admin\/(products|categories|discounts)\/(\d+)$/);
 if(m&&req.method==='PUT'){const type=m[1],id=Number(m[2]),b=await body(req);if(type==='products'){const row={};const map={name:'name',price:'price',category:'category',description:'description',image:'image',emoji:'emoji',active:'active',options:'options',discountActive:'discount_active',discountType:'discount_type',discountValue:'discount_value',showOnDiscounts:'show_on_discounts',showOnFlash:'show_on_flash',showOnBestSellers:'show_on_best_sellers',salesCount:'sales_count'};for(const k of Object.keys(map))if(b[k]!==undefined)row[map[k]]=k==='price'||k==='discountValue'||k==='salesCount'?Number(b[k]):b[k];const out=(await sb('fs_products',`id=eq.${id}`,{method:'PATCH',body:JSON.stringify(row)}))[0];return json(res,200,mapProduct(out));}if(type==='categories'){const row={};const map={name:'name',description:'description',image:'image',active:'active',showOnHome:'show_on_home',sortOrder:'sort_order'};for(const k of Object.keys(map))if(b[k]!==undefined)row[map[k]]=k==='sortOrder'?Number(b[k]):b[k];return json(res,200,mapCategory((await sb('fs_categories',`id=eq.${id}`,{method:'PATCH',body:JSON.stringify(row)}))[0]));}if(type==='discounts'){const row={};const map={code:'code',type:'type',value:'value',minTotal:'min_total',active:'active',firstOrderOnly:'first_order_only',maxUses:'max_uses'};for(const k of Object.keys(map))if(b[k]!==undefined)row[map[k]]=k==='value'||k==='minTotal'||k==='maxUses'?Number(b[k]):b[k];return json(res,200,mapDiscount((await sb('fs_discounts',`id=eq.${id}`,{method:'PATCH',body:JSON.stringify(row)}))[0]));}}
 if(m&&req.method==='DELETE'){const type=m[1],id=Number(m[2]);await sb(`fs_${type}`,`id=eq.${id}`,{method:'DELETE',prefer:'return=minimal'});return json(res,200,{ok:true});}
 m=p.match(/^\/api\/admin\/orders\/(.+)$/);if(m&&req.method==='PUT'){const key=decodeURIComponent(m[1]);const rows=await sb('fs_orders',`select=*&or=(id.eq.${encodeURIComponent(key)},order_number.eq.${encodeURIComponent(key)})&limit=1`);if(!rows?.length)return json(res,404,{error:'Order not found.'});const out=(await sb('fs_orders',`id=eq.${rows[0].id}`,{method:'PATCH',body:JSON.stringify({status:String((await body(req)).status||rows[0].status)})}))[0];return json(res,200,out);}
 return json(res,404,{error:'API route not found'});
}catch(e){console.error('FLASH API error:',e);return json(res,e.status||500,{error:e.message||'Server error.'})}};
