const crypto=require('crypto');
const URL_BASE=String(process.env.SUPABASE_URL||'').replace(/\/$/,'').replace(/\/rest\/v1$/,'');
const KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||process.env.SUPABASE_SECRET_KEY||'';
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'2013';
const SECRET=process.env.FLASH_SECRET||'change-this-secret';
function out(res,s,d){res.statusCode=s;res.setHeader('Content-Type','application/json');res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,DELETE,OPTIONS');res.end(JSON.stringify(d));}
async function body(req){let r='';for await(const c of req)r+=c;if(!r)return{};return JSON.parse(r)}
function cfg(){if(!URL_BASE||!KEY)throw new Error('Supabase environment variables are missing.');}
async function sb(path,opt={}){cfg();const r=await fetch(`${URL_BASE}/rest/v1/${path}`,{...opt,headers:{apikey:KEY,Authorization:`Bearer ${KEY}`,Prefer:opt.prefer||'return=representation',...(opt.headers||{})}});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok){const e=new Error(d?.message||d?.hint||d?.error||`Supabase HTTP ${r.status}`);e.status=r.status;throw e}return d}
const first=async(t,q='')=>{const a=await sb(`${t}?select=*${q}&limit=1`);return a?.[0]||null};
const sign=x=>crypto.createHmac('sha256',SECRET).update(x).digest('hex');
function token(prefix,payload){const p=Buffer.from(JSON.stringify(payload)).toString('base64url');return `${prefix}.${p}.${sign(p)}`}
function verify(req,prefix){const t=String(req.headers.authorization||'').replace(/^Bearer /,'');if(!t.startsWith(prefix+'.'))return null;const a=t.split('.');if(a.length!==3||sign(a[1])!==a[2])return null;try{return JSON.parse(Buffer.from(a[1],'base64url').toString())}catch{return null}}
const user=req=>verify(req,'u');
const admin=req=>{const x=verify(req,'a');return x&&x.role==='admin'&&x.exp>Date.now()};
const mapProduct=x=>({...x,discountActive:x.discount_active,discountType:x.discount_type,discountValue:Number(x.discount_value||0),showOnDiscounts:x.show_on_discounts,showOnFlash:x.show_on_flash,showOnBestSellers:x.show_on_best_sellers,salesCount:Number(x.sales_count||0),options:Array.isArray(x.options)?x.options:[]});
const mapCat=x=>({...x,showOnHome:x.show_on_home,sortOrder:Number(x.sort_order||0)});
const settings=x=>({...x,storeName:x?.store_name||'FLASH STORE',tagline:x?.tagline||'Gaming & Digital Store',whatsapp:x?.whatsapp||'',discord:x?.discord||'',instapay:x?.instapay||'',telda:x?.telda||'',vodafone_cash:x?.vodafone_cash||'',currency:x?.currency||'EGP',announcement:x?.announcement||'⚡ FLASH STORE',heroTitle:x?.hero_title||'FLASH STORE',heroText:x?.hero_text||'Gaming & digital products.'});
module.exports=async(req,res)=>{try{
if(req.method==='OPTIONS')return out(res,204,{});const u=new URL(req.url,'http://localhost');let p=u.pathname.replace(/\/$/,'');
if(p==='/api/store'&&req.method==='GET')return out(res,200,settings(await first('store_settings')));
if(p==='/api/categories'&&req.method==='GET')return out(res,200,(await sb('categories?select=*&active=eq.true&order=sort_order.asc,created_at.asc')).map(mapCat));
if(p==='/api/products'&&req.method==='GET')return out(res,200,(await sb('products?select=*&active=eq.true&order=created_at.desc')).map(mapProduct));
if(p==='/api/auth/register'&&req.method==='POST'){const b=await body(req);const email=String(b.email||'').trim().toLowerCase();if(!b.name||!email||!b.phone||String(b.password||'').length<6)return out(res,400,{error:'Name, email, WhatsApp and password (6+ chars) are required.'});if(await first('users',`&email=eq.${encodeURIComponent(email)}`))return out(res,409,{error:'Email already registered.'});const salt=crypto.randomBytes(16).toString('hex'),hash=crypto.scryptSync(String(b.password),salt,64).toString('hex');const r=(await sb('users',{method:'POST',body:JSON.stringify([{email,name:String(b.name),phone:String(b.phone),password_hash:hash,password_salt:salt,status:'active'}])}))[0];const safe={id:r.id,email:r.email,name:r.name,phone:r.phone};return out(res,200,{token:token('u',safe),user:safe})}
if(p==='/api/auth/login'&&req.method==='POST'){const b=await body(req),u=await first('users',`&email=eq.${encodeURIComponent(String(b.email||'').trim().toLowerCase())}`);if(!u)return out(res,401,{error:'Incorrect email or password.'});const h=crypto.scryptSync(String(b.password||''),u.password_salt,64).toString('hex');if(h!==u.password_hash)return out(res,401,{error:'Incorrect email or password.'});const safe={id:u.id,email:u.email,name:u.name,phone:u.phone};return out(res,200,{token:token('u',safe),user:safe})}
if(p==='/api/auth/me'&&req.method==='GET'){const x=user(req);return x?out(res,200,{user:x}):out(res,401,{error:'Not logged in.'})}
if(p==='/api/admin/login'&&req.method==='POST'){const b=await body(req);if(String(b.password||'')!==ADMIN_PASSWORD)return out(res,401,{error:'Incorrect admin password.'});return out(res,200,{token:token('a',{role:'admin',exp:Date.now()+86400000})})}
if(p.startsWith('/api/admin/')&&!admin(req))return out(res,401,{error:'Unauthorized'});
if(p==='/api/admin/products'&&req.method==='GET')return out(res,200,(await sb('products?select=*&order=created_at.desc')).map(mapProduct));
if(p==='/api/admin/categories'&&req.method==='GET')return out(res,200,(await sb('categories?select=*&order=sort_order.asc,created_at.asc')).map(mapCat));
if(p==='/api/admin/orders'&&req.method==='GET')return out(res,200,await sb('orders?select=*&order=created_at.desc'));
if(p==='/api/admin/users'&&req.method==='GET')return out(res,200,await sb('users?select=id,email,name,phone,status,created_at&order=created_at.desc'));
if(p==='/api/admin/discounts'&&req.method==='GET')return out(res,200,await sb('discounts?select=*&order=created_at.desc'));
if(p==='/api/admin/settings'&&req.method==='GET')return out(res,200,settings(await first('store_settings')));
if(p==='/api/admin/products'&&req.method==='POST'){const b=await body(req);if(!b.name||b.price===undefined)return out(res,400,{error:'Product name and price required.'});const r=(await sb('products',{method:'POST',body:JSON.stringify([{name:String(b.name),price:Number(b.price),category:String(b.category||'Other'),description:String(b.description||''),image:String(b.image||''),emoji:String(b.emoji||'🎮'),active:b.active!==false,discount_active:!!b.discountActive,discount_type:b.discountType==='fixed'?'fixed':'percent',discount_value:Number(b.discountValue||0),options:Array.isArray(b.options)?b.options:[],show_on_discounts:!!b.showOnDiscounts,show_on_flash:!!b.showOnFlash,show_on_best_sellers:!!b.showOnBestSellers}])}))[0];return out(res,200,mapProduct(r))}
if(p==='/api/admin/categories'&&req.method==='POST'){const b=await body(req);if(!b.name)return out(res,400,{error:'Category name required.'});const r=(await sb('categories',{method:'POST',body:JSON.stringify([{name:String(b.name),description:String(b.description||''),image:String(b.image||''),active:b.active!==false,show_on_home:b.showOnHome!==false,sort_order:Number(b.sortOrder||0)}])}))[0];return out(res,200,mapCat(r))}
if(p==='/api/admin/discounts'&&req.method==='POST'){const b=await body(req);const code=String(b.code||'').trim().toUpperCase();if(!code||b.value===undefined)return out(res,400,{error:'Code and value required.'});const r=(await sb('discounts',{method:'POST',body:JSON.stringify([{code,type:b.type==='fixed'?'fixed':'percent',value:Number(b.value),min_total:Number(b.minTotal||0),active:b.active!==false,first_order_only:!!b.firstOrderOnly,max_uses:Number(b.maxUses||0),used_count:0}])}))[0];return out(res,200,r)}
if(p==='/api/admin/settings'&&req.method==='PUT'){const b=await body(req),old=await first('store_settings');const row={store_name:b.storeName,tagline:b.tagline,whatsapp:b.whatsapp,discord:b.discord,instapay:b.instapay,telda:b.telda,vodafone_cash:b.vodafone_cash,currency:b.currency,announcement:b.announcement,hero_title:b.heroTitle,hero_text:b.heroText};Object.keys(row).forEach(k=>row[k]===undefined&&delete row[k]);let r;if(old)r=(await sb(`store_settings?id=eq.${old.id}`,{method:'PATCH',body:JSON.stringify(row)}))[0];else r=(await sb('store_settings',{method:'POST',body:JSON.stringify([{id:1,...row}])}))[0];return out(res,200,settings(r))}
let m=p.match(/^\/api\/admin\/(products|categories|discounts)\/(\d+)$/);if(m&&(req.method==='PUT'||req.method==='DELETE')){const type=m[1],id=m[2];if(req.method==='DELETE'){await sb(`${type}?id=eq.${id}`,{method:'DELETE',prefer:'return=minimal'});return out(res,200,{ok:true})}const b=await body(req),row={...b};if(type==='products'){if('discountActive'in b)row.discount_active=b.discountActive;if('discountType'in b)row.discount_type=b.discountType;if('discountValue'in b)row.discount_value=Number(b.discountValue);delete row.discountActive;delete row.discountType;delete row.discountValue}if(type==='categories'){if('showOnHome'in b)row.show_on_home=b.showOnHome;if('sortOrder'in b)row.sort_order=Number(b.sortOrder);delete row.showOnHome;delete row.sortOrder}if(type==='discounts'){if('minTotal'in b)row.min_total=Number(b.minTotal);if('firstOrderOnly'in b)row.first_order_only=b.firstOrderOnly;if('maxUses'in b)row.max_uses=Number(b.maxUses);delete row.minTotal;delete row.firstOrderOnly;delete row.maxUses}return out(res,200,(await sb(`${type}?id=eq.${id}`,{method:'PATCH',body:JSON.stringify(row)}))[0])}
return out(res,404,{error:'API route not found'});
}catch(e){console.error(e);return out(res,e.status||500,{error:e.message||'Server error'})}};
